/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gq.ged.user.tmodel;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-01-18")
public class UserRetrieveThriftForm implements org.apache.thrift.TBase<UserRetrieveThriftForm, UserRetrieveThriftForm._Fields>, java.io.Serializable, Cloneable, Comparable<UserRetrieveThriftForm> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UserRetrieveThriftForm");

  private static final org.apache.thrift.protocol.TField MOBILE_FIELD_DESC = new org.apache.thrift.protocol.TField("mobile", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("code", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField NEW_PASSWORD_FIELD_DESC = new org.apache.thrift.protocol.TField("newPassword", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField CONFIRM_PASSWORD_FIELD_DESC = new org.apache.thrift.protocol.TField("confirmPassword", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new UserRetrieveThriftFormStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new UserRetrieveThriftFormTupleSchemeFactory();

  public String mobile; // required
  public String code; // required
  public String newPassword; // required
  public String confirmPassword; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MOBILE((short)1, "mobile"),
    CODE((short)2, "code"),
    NEW_PASSWORD((short)3, "newPassword"),
    CONFIRM_PASSWORD((short)4, "confirmPassword");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MOBILE
          return MOBILE;
        case 2: // CODE
          return CODE;
        case 3: // NEW_PASSWORD
          return NEW_PASSWORD;
        case 4: // CONFIRM_PASSWORD
          return CONFIRM_PASSWORD;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) {
          throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      }
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MOBILE, new org.apache.thrift.meta_data.FieldMetaData("mobile", org.apache.thrift.TFieldRequirementType.DEFAULT,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CODE, new org.apache.thrift.meta_data.FieldMetaData("code", org.apache.thrift.TFieldRequirementType.DEFAULT,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NEW_PASSWORD, new org.apache.thrift.meta_data.FieldMetaData("newPassword", org.apache.thrift.TFieldRequirementType.DEFAULT,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CONFIRM_PASSWORD, new org.apache.thrift.meta_data.FieldMetaData("confirmPassword", org.apache.thrift.TFieldRequirementType.DEFAULT,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UserRetrieveThriftForm.class, metaDataMap);
  }

  public UserRetrieveThriftForm() {
  }

  public UserRetrieveThriftForm(
    String mobile,
    String code,
    String newPassword,
    String confirmPassword)
  {
    this();
    this.mobile = mobile;
    this.code = code;
    this.newPassword = newPassword;
    this.confirmPassword = confirmPassword;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UserRetrieveThriftForm(UserRetrieveThriftForm other) {
    if (other.isSetMobile()) {
      this.mobile = other.mobile;
    }
    if (other.isSetCode()) {
      this.code = other.code;
    }
    if (other.isSetNewPassword()) {
      this.newPassword = other.newPassword;
    }
    if (other.isSetConfirmPassword()) {
      this.confirmPassword = other.confirmPassword;
    }
  }

  @Override
  public UserRetrieveThriftForm deepCopy() {
    return new UserRetrieveThriftForm(this);
  }

  @Override
  public void clear() {
    this.mobile = null;
    this.code = null;
    this.newPassword = null;
    this.confirmPassword = null;
  }

  public String getMobile() {
    return this.mobile;
  }

  public UserRetrieveThriftForm setMobile(String mobile) {
    this.mobile = mobile;
    return this;
  }

  public void unsetMobile() {
    this.mobile = null;
  }

  /** Returns true if field mobile is set (has been assigned a value) and false otherwise */
  public boolean isSetMobile() {
    return this.mobile != null;
  }

  public void setMobileIsSet(boolean value) {
    if (!value) {
      this.mobile = null;
    }
  }

  public String getCode() {
    return this.code;
  }

  public UserRetrieveThriftForm setCode(String code) {
    this.code = code;
    return this;
  }

  public void unsetCode() {
    this.code = null;
  }

  /** Returns true if field code is set (has been assigned a value) and false otherwise */
  public boolean isSetCode() {
    return this.code != null;
  }

  public void setCodeIsSet(boolean value) {
    if (!value) {
      this.code = null;
    }
  }

  public String getNewPassword() {
    return this.newPassword;
  }

  public UserRetrieveThriftForm setNewPassword(String newPassword) {
    this.newPassword = newPassword;
    return this;
  }

  public void unsetNewPassword() {
    this.newPassword = null;
  }

  /** Returns true if field newPassword is set (has been assigned a value) and false otherwise */
  public boolean isSetNewPassword() {
    return this.newPassword != null;
  }

  public void setNewPasswordIsSet(boolean value) {
    if (!value) {
      this.newPassword = null;
    }
  }

  public String getConfirmPassword() {
    return this.confirmPassword;
  }

  public UserRetrieveThriftForm setConfirmPassword(String confirmPassword) {
    this.confirmPassword = confirmPassword;
    return this;
  }

  public void unsetConfirmPassword() {
    this.confirmPassword = null;
  }

  /** Returns true if field confirmPassword is set (has been assigned a value) and false otherwise */
  public boolean isSetConfirmPassword() {
    return this.confirmPassword != null;
  }

  public void setConfirmPasswordIsSet(boolean value) {
    if (!value) {
      this.confirmPassword = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MOBILE:
      if (value == null) {
        unsetMobile();
      } else {
        setMobile((String)value);
      }
      break;

    case CODE:
      if (value == null) {
        unsetCode();
      } else {
        setCode((String)value);
      }
      break;

    case NEW_PASSWORD:
      if (value == null) {
        unsetNewPassword();
      } else {
        setNewPassword((String)value);
      }
      break;

    case CONFIRM_PASSWORD:
      if (value == null) {
        unsetConfirmPassword();
      } else {
        setConfirmPassword((String)value);
      }
      break;

    }
  }

  @Override
  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MOBILE:
      return getMobile();

    case CODE:
      return getCode();

    case NEW_PASSWORD:
      return getNewPassword();

    case CONFIRM_PASSWORD:
      return getConfirmPassword();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MOBILE:
      return isSetMobile();
    case CODE:
      return isSetCode();
    case NEW_PASSWORD:
      return isSetNewPassword();
    case CONFIRM_PASSWORD:
      return isSetConfirmPassword();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null) {
        return false;
    }
    if (that instanceof UserRetrieveThriftForm) {
        return this.equals((UserRetrieveThriftForm)that);
    }
    return false;
  }

  public boolean equals(UserRetrieveThriftForm that) {
    if (that == null) {
        return false;
    }
    if (this == that) {
        return true;
    }

    boolean this_present_mobile = true && this.isSetMobile();
    boolean that_present_mobile = true && that.isSetMobile();
    if (this_present_mobile || that_present_mobile) {
      if (!(this_present_mobile && that_present_mobile)) {
          return false;
      }
      if (!this.mobile.equals(that.mobile)) {
          return false;
      }
    }

    boolean this_present_code = true && this.isSetCode();
    boolean that_present_code = true && that.isSetCode();
    if (this_present_code || that_present_code) {
      if (!(this_present_code && that_present_code)) {
          return false;
      }
      if (!this.code.equals(that.code)) {
          return false;
      }
    }

    boolean this_present_newPassword = true && this.isSetNewPassword();
    boolean that_present_newPassword = true && that.isSetNewPassword();
    if (this_present_newPassword || that_present_newPassword) {
      if (!(this_present_newPassword && that_present_newPassword)) {
          return false;
      }
      if (!this.newPassword.equals(that.newPassword)) {
          return false;
      }
    }

    boolean this_present_confirmPassword = true && this.isSetConfirmPassword();
    boolean that_present_confirmPassword = true && that.isSetConfirmPassword();
    if (this_present_confirmPassword || that_present_confirmPassword) {
      if (!(this_present_confirmPassword && that_present_confirmPassword)) {
          return false;
      }
      if (!this.confirmPassword.equals(that.confirmPassword)) {
          return false;
      }
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetMobile()) ? 131071 : 524287);
    if (isSetMobile()) {
        hashCode = hashCode * 8191 + mobile.hashCode();
    }

    hashCode = hashCode * 8191 + ((isSetCode()) ? 131071 : 524287);
    if (isSetCode()) {
        hashCode = hashCode * 8191 + code.hashCode();
    }

    hashCode = hashCode * 8191 + ((isSetNewPassword()) ? 131071 : 524287);
    if (isSetNewPassword()) {
        hashCode = hashCode * 8191 + newPassword.hashCode();
    }

    hashCode = hashCode * 8191 + ((isSetConfirmPassword()) ? 131071 : 524287);
    if (isSetConfirmPassword()) {
        hashCode = hashCode * 8191 + confirmPassword.hashCode();
    }

    return hashCode;
  }

  @Override
  public int compareTo(UserRetrieveThriftForm other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMobile()).compareTo(other.isSetMobile());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMobile()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mobile, other.mobile);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCode()).compareTo(other.isSetCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.code, other.code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNewPassword()).compareTo(other.isSetNewPassword());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNewPassword()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.newPassword, other.newPassword);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetConfirmPassword()).compareTo(other.isSetConfirmPassword());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetConfirmPassword()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.confirmPassword, other.confirmPassword);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("UserRetrieveThriftForm(");
    boolean first = true;

    sb.append("mobile:");
    if (this.mobile == null) {
      sb.append("null");
    } else {
      sb.append(this.mobile);
    }
    first = false;
    if (!first) {
        sb.append(", ");
    }
    sb.append("code:");
    if (this.code == null) {
      sb.append("null");
    } else {
      sb.append(this.code);
    }
    first = false;
    if (!first) {
        sb.append(", ");
    }
    sb.append("newPassword:");
    if (this.newPassword == null) {
      sb.append("null");
    } else {
      sb.append(this.newPassword);
    }
    first = false;
    if (!first) {
        sb.append(", ");
    }
    sb.append("confirmPassword:");
    if (this.confirmPassword == null) {
      sb.append("null");
    } else {
      sb.append(this.confirmPassword);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UserRetrieveThriftFormStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public UserRetrieveThriftFormStandardScheme getScheme() {
      return new UserRetrieveThriftFormStandardScheme();
    }
  }

  private static class UserRetrieveThriftFormStandardScheme extends org.apache.thrift.scheme.StandardScheme<UserRetrieveThriftForm> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, UserRetrieveThriftForm struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MOBILE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.mobile = iprot.readString();
              struct.setMobileIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.code = iprot.readString();
              struct.setCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // NEW_PASSWORD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.newPassword = iprot.readString();
              struct.setNewPasswordIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CONFIRM_PASSWORD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.confirmPassword = iprot.readString();
              struct.setConfirmPasswordIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, UserRetrieveThriftForm struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.mobile != null) {
        oprot.writeFieldBegin(MOBILE_FIELD_DESC);
        oprot.writeString(struct.mobile);
        oprot.writeFieldEnd();
      }
      if (struct.code != null) {
        oprot.writeFieldBegin(CODE_FIELD_DESC);
        oprot.writeString(struct.code);
        oprot.writeFieldEnd();
      }
      if (struct.newPassword != null) {
        oprot.writeFieldBegin(NEW_PASSWORD_FIELD_DESC);
        oprot.writeString(struct.newPassword);
        oprot.writeFieldEnd();
      }
      if (struct.confirmPassword != null) {
        oprot.writeFieldBegin(CONFIRM_PASSWORD_FIELD_DESC);
        oprot.writeString(struct.confirmPassword);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UserRetrieveThriftFormTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public UserRetrieveThriftFormTupleScheme getScheme() {
      return new UserRetrieveThriftFormTupleScheme();
    }
  }

  private static class UserRetrieveThriftFormTupleScheme extends org.apache.thrift.scheme.TupleScheme<UserRetrieveThriftForm> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UserRetrieveThriftForm struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetMobile()) {
        optionals.set(0);
      }
      if (struct.isSetCode()) {
        optionals.set(1);
      }
      if (struct.isSetNewPassword()) {
        optionals.set(2);
      }
      if (struct.isSetConfirmPassword()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetMobile()) {
        oprot.writeString(struct.mobile);
      }
      if (struct.isSetCode()) {
        oprot.writeString(struct.code);
      }
      if (struct.isSetNewPassword()) {
        oprot.writeString(struct.newPassword);
      }
      if (struct.isSetConfirmPassword()) {
        oprot.writeString(struct.confirmPassword);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UserRetrieveThriftForm struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.mobile = iprot.readString();
        struct.setMobileIsSet(true);
      }
      if (incoming.get(1)) {
        struct.code = iprot.readString();
        struct.setCodeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.newPassword = iprot.readString();
        struct.setNewPasswordIsSet(true);
      }
      if (incoming.get(3)) {
        struct.confirmPassword = iprot.readString();
        struct.setConfirmPasswordIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

