package com.resoft.outinterface.SV.client2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4 2016-05-12T15:04:46.928+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://workorder.controller.application.mobile.com/", name = "WorkOrderControllerDelegate")
@XmlSeeAlso({ ObjectFactory.class })
public interface WorkOrderControllerDelegate {

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "orderDistribute", targetNamespace = "http://workorder.controller.application.mobile.com/", className = "com.resoft.outinterface.SV.client2.OrderDistribute")
	@WebMethod
	@ResponseWrapper(localName = "orderDistributeResponse", targetNamespace = "http://workorder.controller.application.mobile.com/", className = "com.resoft.outinterface.SV.client2.OrderDistributeResponse")
	public CommonVO orderDistribute(
			@WebParam(name = "arg0", targetNamespace = "") com.resoft.outinterface.SV.client2.WorkOrderDto arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.mobile.application.controller.workorder.CommonVO
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "workOrderTransfer", targetNamespace = "http://workorder.controller.application.mobile.com/", className = "com.resoft.outinterface.SV.client2.WorkOrderTransfer")
	@ResponseWrapper(localName = "workOrderTransferResponse", targetNamespace = "http://workorder.controller.application.mobile.com/", className = "com.resoft.outinterface.SV.client2.WorkOrderTransferResponse")
	public CommonVO workOrderTransfer(@WebParam(name = "arg0", targetNamespace = "") WorkOrderTransferVO arg0);

}
