package com.resoft.outinterface.SV.client2;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.thinkgem.jeesite.common.config.Global;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-05-12T15:04:46.934+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "WorkOrderControllerService", 
                  targetNamespace = "http://workorder.controller.application.mobile.com/") 
public class WorkOrderControllerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://workorder.controller.application.mobile.com/", "WorkOrderControllerService");
    public final static QName WorkOrderControllerPort = new QName("http://workorder.controller.application.mobile.com/", "WorkOrderControllerPort");
    static {
        URL url = null;
        try {
            url = new URL(Global.getConfig("SV"));
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WorkOrderControllerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://180.166.238.14:17090/pushwin/WorkOrderControllerPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WorkOrderControllerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WorkOrderControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorkOrderControllerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WorkOrderControllerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WorkOrderControllerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WorkOrderControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WorkOrderControllerDelegate
     */
    @WebEndpoint(name = "WorkOrderControllerPort")
    public WorkOrderControllerDelegate getWorkOrderControllerPort() {
        return super.getPort(WorkOrderControllerPort, WorkOrderControllerDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WorkOrderControllerDelegate
     */
    @WebEndpoint(name = "WorkOrderControllerPort")
    public WorkOrderControllerDelegate getWorkOrderControllerPort(WebServiceFeature... features) {
        return super.getPort(WorkOrderControllerPort, WorkOrderControllerDelegate.class, features);
    }

}
