/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gq.ged.message.tmodel;


import org.apache.thrift.TEnum;

public enum MsgTypeEnum implements TEnum {
  MSG_TYPE_REGISTER(1),
  MSG_TYPE_FORGET(2);

  private final int value;

  private MsgTypeEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MsgTypeEnum findByValue(int value) {
    switch (value) {
      case 1:
        return MSG_TYPE_REGISTER;
      case 2:
        return MSG_TYPE_FORGET;
      default:
        return null;
    }
  }
}
