//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 06:41:27 PM CST 
//


package com.resoft.outinterface.cn.com.experian.entry.request.body;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CoAppInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoAppInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="CoApp_MChild_num" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CoApp_marital_status" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CoApp_live_status" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CoApp_IsHaveHouse" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CoApp_age" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CoApp_FChild_num" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CoApp_IsInvolved" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CoApp_ID_start" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="CoApp_IBL_Flag" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CoApp_MobilPhoone" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CoApp_sex" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CoApp_IsFixHouse" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CoApp_ID_Due_Date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoAppInfo", propOrder = {
    "coAppMChildNum",
    "coAppMaritalStatus",
    "coAppLiveStatus",
    "coAppIsHaveHouse",
    "coAppAge",
    "coAppFChildNum",
    "coAppIsInvolved",
    "coAppIDStart",
    "coAppIBLFlag",
    "coAppMobilPhoone",
    "coAppSex",
    "coAppIsFixHouse",
    "coAppIDDueDate"
})
public class CoAppInfo {

    @XmlElement(name = "CoApp_MChild_num")
    protected BigDecimal coAppMChildNum;
    @XmlElement(name = "CoApp_marital_status")
    protected BigDecimal coAppMaritalStatus;
    @XmlElement(name = "CoApp_live_status")
    protected BigDecimal coAppLiveStatus;
    @XmlElement(name = "CoApp_IsHaveHouse")
    protected BigDecimal coAppIsHaveHouse;
    @XmlElement(name = "CoApp_age")
    protected BigDecimal coAppAge;
    @XmlElement(name = "CoApp_FChild_num")
    protected BigDecimal coAppFChildNum;
    @XmlElement(name = "CoApp_IsInvolved")
    protected BigDecimal coAppIsInvolved;
    @XmlElement(name = "CoApp_ID_start")
    @XmlSchemaType(name = "date")
    protected String coAppIDStart;
    @XmlElement(name = "CoApp_IBL_Flag")
    protected BigDecimal coAppIBLFlag;
    @XmlElement(name = "CoApp_MobilPhoone")
    protected BigDecimal coAppMobilPhoone;
    @XmlElement(name = "CoApp_sex")
    protected String coAppSex;
    @XmlElement(name = "CoApp_IsFixHouse")
    protected BigDecimal coAppIsFixHouse;
    @XmlElement(name = "CoApp_ID_Due_Date")
    @XmlSchemaType(name = "date")
    protected String coAppIDDueDate;

    /**
     * Gets the value of the coAppMChildNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoAppMChildNum() {
        return coAppMChildNum;
    }

    /**
     * Sets the value of the coAppMChildNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoAppMChildNum(BigDecimal value) {
        this.coAppMChildNum = value;
    }

    /**
     * Gets the value of the coAppMaritalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoAppMaritalStatus() {
        return coAppMaritalStatus;
    }

    /**
     * Sets the value of the coAppMaritalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoAppMaritalStatus(BigDecimal value) {
        this.coAppMaritalStatus = value;
    }

    /**
     * Gets the value of the coAppLiveStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoAppLiveStatus() {
        return coAppLiveStatus;
    }

    /**
     * Sets the value of the coAppLiveStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoAppLiveStatus(BigDecimal value) {
        this.coAppLiveStatus = value;
    }

    /**
     * Gets the value of the coAppIsHaveHouse property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoAppIsHaveHouse() {
        return coAppIsHaveHouse;
    }

    /**
     * Sets the value of the coAppIsHaveHouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    
    public void setCoAppIsHaveHouse(BigDecimal value) {
        this.coAppIsHaveHouse = value;
    }


	/**
     * Gets the value of the coAppAge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoAppAge() {
        return coAppAge;
    }

    /**
     * Sets the value of the coAppAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoAppAge(BigDecimal value) {
        this.coAppAge = value;
    }

    /**
     * Gets the value of the coAppFChildNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoAppFChildNum() {
        return coAppFChildNum;
    }

    /**
     * Sets the value of the coAppFChildNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoAppFChildNum(BigDecimal value) {
        this.coAppFChildNum = value;
    }

    /**
     * Gets the value of the coAppIsInvolved property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoAppIsInvolved() {
        return coAppIsInvolved;
    }

    /**
     * Sets the value of the coAppIsInvolved property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoAppIsInvolved(BigDecimal value) {
        this.coAppIsInvolved = value;
    }

    /**
     * Gets the value of the coAppIDStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    

    

    /**
     * Gets the value of the coAppIBLFlag property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoAppIBLFlag() {
        return coAppIBLFlag;
    }

    public String getCoAppIDStart() {
		return coAppIDStart;
	}

	public void setCoAppIDStart(String coAppIDStart) {
		this.coAppIDStart = coAppIDStart;
	}

	public void setCoAppIDDueDate(String coAppIDDueDate) {
		this.coAppIDDueDate = coAppIDDueDate;
	}

	/**
     * Sets the value of the coAppIBLFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoAppIBLFlag(BigDecimal value) {
        this.coAppIBLFlag = value;
    }

    /**
     * Gets the value of the coAppMobilPhoone property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoAppMobilPhoone() {
        return coAppMobilPhoone;
    }

    /**
     * Sets the value of the coAppMobilPhoone property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoAppMobilPhoone(BigDecimal value) {
        this.coAppMobilPhoone = value;
    }

    /**
     * Gets the value of the coAppSex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoAppSex() {
        return coAppSex;
    }

    /**
     * Sets the value of the coAppSex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoAppSex(String value) {
        this.coAppSex = value;
    }

    /**
     * Gets the value of the coAppIsFixHouse property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoAppIsFixHouse() {
        return coAppIsFixHouse;
    }

    /**
     * Sets the value of the coAppIsFixHouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoAppIsFixHouse(BigDecimal value) {
        this.coAppIsFixHouse = value;
    }


	public String getCoAppIDDueDate() {
		return coAppIDDueDate;
	}


}
