//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 06:41:27 PM CST 
//

package com.resoft.outinterface.cn.com.experian.entry.request.body;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for GuAppInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GuAppInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="GuApp_SharePropertion" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_ContributYear" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_Loan_Balance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_MChild_num" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_HouseYear" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_AmountMultiple" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_IsBreak_Pipeline_Persion" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_Average_Pipeline_Persion" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_work_year" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_marital_status" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_live_status" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_Pipeline_Print" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="GuApp_Plpeline_End" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="GuApp_Plpeline_Start" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="GuApp_IsPipelineBreak" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_IsHaveHouse" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_Age" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_Fchild_num" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_Spouse_IsIBL" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_Spouse_age" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_IsInvolved" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_ID_start" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="GuApp_IsIBL" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_MobilePhone" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_city" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GuApp_industry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GuApp_Sex" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GuApp_IsFixHouse" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="GuApp_ID_Due_Time" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="GuApp_education" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GuAppInfo", propOrder = {
    "guAppSharePropertion",
    "guAppContributYear",
    "guAppLoanBalance",
    "guAppMChildNum",
    "guAppHouseYear",
    "guAppAmountMultiple",
    "guAppIsBreakPipelinePersion",
    "guAppAveragePipelinePersion",
    "guAppWorkYear",
    "guAppMaritalStatus",
    "guAppLiveStatus",
    "guAppPipelinePrint",
    "guAppPlpelineEnd",
    "guAppPlpelineStart",
    "guAppIsPipelineBreak",
    "guAppIsHaveHouse",
    "guAppAge",
    "guAppFchildNum",
    "guAppSpouseIsIBL",
    "guAppSpouseAge",
    "guAppIsInvolved",
    "guAppIDStart",
    "guAppIsIBL",
    "guAppMobilePhone",
    "guAppCity",
    "guAppIndustry",
    "guAppSex",
    "guAppIsFixHouse",
    "guAppIDDueTime",
    "guAppEducation"
})
public class GuAppInfo {

    @XmlElement(name = "GuApp_SharePropertion")
    protected BigDecimal guAppSharePropertion;
    @XmlElement(name = "GuApp_ContributYear")
    protected BigDecimal guAppContributYear;
    @XmlElement(name = "GuApp_Loan_Balance")
    protected BigDecimal guAppLoanBalance;
    @XmlElement(name = "GuApp_MChild_num")
    protected BigDecimal guAppMChildNum;
    @XmlElement(name = "GuApp_HouseYear")
    protected BigDecimal guAppHouseYear;
    @XmlElement(name = "GuApp_AmountMultiple")
    protected BigDecimal guAppAmountMultiple;
    @XmlElement(name = "GuApp_IsBreak_Pipeline_Persion")
    protected BigDecimal guAppIsBreakPipelinePersion;
    @XmlElement(name = "GuApp_Average_Pipeline_Persion")
    protected BigDecimal guAppAveragePipelinePersion;
    @XmlElement(name = "GuApp_work_year")
    protected BigDecimal guAppWorkYear;
    @XmlElement(name = "GuApp_marital_status")
    protected BigDecimal guAppMaritalStatus;
    @XmlElement(name = "GuApp_live_status")
    protected BigDecimal guAppLiveStatus;
    @XmlElement(name = "GuApp_Pipeline_Print")
    @XmlSchemaType(name = "date")
    protected String guAppPipelinePrint;
    @XmlElement(name = "GuApp_Plpeline_End")
    @XmlSchemaType(name = "date")
    protected String guAppPlpelineEnd;
    @XmlElement(name = "GuApp_Plpeline_Start")
    @XmlSchemaType(name = "date")
    protected String guAppPlpelineStart;
    @XmlElement(name = "GuApp_IsPipelineBreak")
    protected BigDecimal guAppIsPipelineBreak;
    @XmlElement(name = "GuApp_IsHaveHouse")
    protected BigDecimal guAppIsHaveHouse;
    @XmlElement(name = "GuApp_Age")
    protected BigDecimal guAppAge;
    @XmlElement(name = "GuApp_Fchild_num")
    protected BigDecimal guAppFchildNum;
    @XmlElement(name = "GuApp_Spouse_IsIBL")
    protected BigDecimal guAppSpouseIsIBL;
    @XmlElement(name = "GuApp_Spouse_age")
    protected BigDecimal guAppSpouseAge;
    @XmlElement(name = "GuApp_IsInvolved")
    protected BigDecimal guAppIsInvolved;
    @XmlElement(name = "GuApp_ID_start")
    @XmlSchemaType(name = "date")
    protected String guAppIDStart;
    @XmlElement(name = "GuApp_IsIBL")
    protected BigDecimal guAppIsIBL;
    @XmlElement(name = "GuApp_MobilePhone")
    protected BigDecimal guAppMobilePhone;
    @XmlElement(name = "GuApp_city")
    protected String guAppCity;
    @XmlElement(name = "GuApp_industry")
    protected String guAppIndustry;
    @XmlElement(name = "GuApp_Sex")
    protected String guAppSex;
    @XmlElement(name = "GuApp_IsFixHouse")
    protected BigDecimal guAppIsFixHouse;
    @XmlElement(name = "GuApp_ID_Due_Time")
    @XmlSchemaType(name = "date")
    protected String guAppIDDueTime;
    @XmlElement(name = "GuApp_education")
    protected BigDecimal guAppEducation;

    /**
     * Gets the value of the guAppSharePropertion property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppSharePropertion() {
        return guAppSharePropertion;
    }

    /**
     * Sets the value of the guAppSharePropertion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppSharePropertion(BigDecimal value) {
        this.guAppSharePropertion = value;
    }


	/**
     * Gets the value of the guAppContributYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppContributYear() {
        return guAppContributYear;
    }

    /**
     * Sets the value of the guAppContributYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppContributYear(BigDecimal value) {
        this.guAppContributYear = value;
    }

    /**
     * Gets the value of the guAppLoanBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppLoanBalance() {
        return guAppLoanBalance;
    }

    /**
     * Sets the value of the guAppLoanBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppLoanBalance(BigDecimal value) {
        this.guAppLoanBalance = value;
    }

    /**
     * Gets the value of the guAppMChildNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppMChildNum() {
        return guAppMChildNum;
    }

    /**
     * Sets the value of the guAppMChildNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppMChildNum(BigDecimal value) {
        this.guAppMChildNum = value;
    }

    /**
     * Gets the value of the guAppHouseYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppHouseYear() {
        return guAppHouseYear;
    }

    /**
     * Sets the value of the guAppHouseYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppHouseYear(BigDecimal value) {
        this.guAppHouseYear = value;
    }

    /**
     * Gets the value of the guAppAmountMultiple property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppAmountMultiple() {
        return guAppAmountMultiple;
    }

    /**
     * Sets the value of the guAppAmountMultiple property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppAmountMultiple(BigDecimal value) {
        this.guAppAmountMultiple = value;
    }

    /**
     * Gets the value of the guAppIsBreakPipelinePersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppIsBreakPipelinePersion() {
        return guAppIsBreakPipelinePersion;
    }

    /**
     * Sets the value of the guAppIsBreakPipelinePersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppIsBreakPipelinePersion(BigDecimal value) {
        this.guAppIsBreakPipelinePersion = value;
    }

    /**
     * Gets the value of the guAppAveragePipelinePersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppAveragePipelinePersion() {
        return guAppAveragePipelinePersion;
    }

    /**
     * Sets the value of the guAppAveragePipelinePersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppAveragePipelinePersion(BigDecimal value) {
        this.guAppAveragePipelinePersion = value;
    }

    /**
     * Gets the value of the guAppWorkYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppWorkYear() {
        return guAppWorkYear;
    }

    /**
     * Sets the value of the guAppWorkYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppWorkYear(BigDecimal value) {
        this.guAppWorkYear = value;
    }

    /**
     * Gets the value of the guAppMaritalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppMaritalStatus() {
        return guAppMaritalStatus;
    }

    /**
     * Sets the value of the guAppMaritalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppMaritalStatus(BigDecimal value) {
        this.guAppMaritalStatus = value;
    }

    /**
     * Gets the value of the guAppLiveStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppLiveStatus() {
        return guAppLiveStatus;
    }

    /**
     * Sets the value of the guAppLiveStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppLiveStatus(BigDecimal value) {
        this.guAppLiveStatus = value;
    }

    
    /**
     * Gets the value of the guAppIsPipelineBreak property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppIsPipelineBreak() {
        return guAppIsPipelineBreak;
    }

    /**
     * Sets the value of the guAppIsPipelineBreak property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppIsPipelineBreak(BigDecimal value) {
        this.guAppIsPipelineBreak = value;
    }

    /**
     * Gets the value of the guAppIsHaveHouse property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppIsHaveHouse() {
        return guAppIsHaveHouse;
    }

    /**
     * Sets the value of the guAppIsHaveHouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppIsHaveHouse(BigDecimal value) {
        this.guAppIsHaveHouse = value;
    }

    /**
     * Gets the value of the guAppAge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppAge() {
        return guAppAge;
    }

    /**
     * Sets the value of the guAppAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppAge(BigDecimal value) {
        this.guAppAge = value;
    }

    /**
     * Gets the value of the guAppFchildNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppFchildNum() {
        return guAppFchildNum;
    }

    /**
     * Sets the value of the guAppFchildNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppFchildNum(BigDecimal value) {
        this.guAppFchildNum = value;
    }

    /**
     * Gets the value of the guAppSpouseIsIBL property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppSpouseIsIBL() {
        return guAppSpouseIsIBL;
    }

    /**
     * Sets the value of the guAppSpouseIsIBL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppSpouseIsIBL(BigDecimal value) {
        this.guAppSpouseIsIBL = value;
    }

    /**
     * Gets the value of the guAppSpouseAge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppSpouseAge() {
        return guAppSpouseAge;
    }

    /**
     * Sets the value of the guAppSpouseAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppSpouseAge(BigDecimal value) {
        this.guAppSpouseAge = value;
    }

    /**
     * Gets the value of the guAppIsInvolved property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppIsInvolved() {
        return guAppIsInvolved;
    }

    /**
     * Sets the value of the guAppIsInvolved property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppIsInvolved(BigDecimal value) {
        this.guAppIsInvolved = value;
    }



    /**
     * Gets the value of the guAppIsIBL property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppIsIBL() {
        return guAppIsIBL;
    }

    /**
     * Sets the value of the guAppIsIBL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppIsIBL(BigDecimal value) {
        this.guAppIsIBL = value;
    }

    /**
     * Gets the value of the guAppMobilePhone property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppMobilePhone() {
        return guAppMobilePhone;
    }

    /**
     * Sets the value of the guAppMobilePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppMobilePhone(BigDecimal value) {
        this.guAppMobilePhone = value;
    }

    /**
     * Gets the value of the guAppCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuAppCity() {
        return guAppCity;
    }

    /**
     * Sets the value of the guAppCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuAppCity(String value) {
        this.guAppCity = value;
    }

    /**
     * Gets the value of the guAppIndustry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuAppIndustry() {
        return guAppIndustry;
    }

    /**
     * Sets the value of the guAppIndustry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuAppIndustry(String value) {
        this.guAppIndustry = value;
    }

    /**
     * Gets the value of the guAppSex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuAppSex() {
        return guAppSex;
    }

    /**
     * Sets the value of the guAppSex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuAppSex(String value) {
        this.guAppSex = value;
    }

    /**
     * Gets the value of the guAppIsFixHouse property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppIsFixHouse() {
        return guAppIsFixHouse;
    }

    /**
     * Sets the value of the guAppIsFixHouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppIsFixHouse(BigDecimal value) {
        this.guAppIsFixHouse = value;
    }

   
    /**
     * Gets the value of the guAppEducation property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuAppEducation() {
        return guAppEducation;
    }

    /**
     * Sets the value of the guAppEducation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuAppEducation(BigDecimal value) {
        this.guAppEducation = value;
    }

	public String getGuAppPipelinePrint() {
		return guAppPipelinePrint;
	}

	public void setGuAppPipelinePrint(String guAppPipelinePrint) {
		this.guAppPipelinePrint = guAppPipelinePrint;
	}

	public String getGuAppPlpelineEnd() {
		return guAppPlpelineEnd;
	}

	public void setGuAppPlpelineEnd(String guAppPlpelineEnd) {
		this.guAppPlpelineEnd = guAppPlpelineEnd;
	}

	public String getGuAppPlpelineStart() {
		return guAppPlpelineStart;
	}

	public void setGuAppPlpelineStart(String guAppPlpelineStart) {
		this.guAppPlpelineStart = guAppPlpelineStart;
	}

	public String getGuAppIDStart() {
		return guAppIDStart;
	}

	public void setGuAppIDStart(String guAppIDStart) {
		this.guAppIDStart = guAppIDStart;
	}

	public String getGuAppIDDueTime() {
		return guAppIDDueTime;
	}

	public void setGuAppIDDueTime(String guAppIDDueTime) {
		this.guAppIDDueTime = guAppIDDueTime;
	}

}
