//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 06:41:27 PM CST 
//

package com.resoft.outinterface.cn.com.experian.entry.request.body;

import java.math.BigDecimal;
import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for LoanInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoanInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="LoanId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsCarKeepPaper" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="AssureWay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LoanaAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="LoanApplyDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="CarValue" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="TransferNum" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CarType" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="AS_Fraud" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CarUsedYear" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="IsProcedureCom" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="IsCarstatusNormal" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CarQuality" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="AssureType" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="House_ES" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="HouseUsedYear" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="House_City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="House_CityLevel" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="House_Use" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Mortgage_Type" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Pledge" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="IsHouseOnly" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="IsDispute" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="IsHouseKeepPaper" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="HouseMortgage_Type" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="IsQueryFiles" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Refund_Way" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Refund_Term" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="LoanDueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Loan_term" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="IsTransfRec" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="DueDispos" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Refund_Month" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoanInfo", propOrder = {
    "loanId",
    "assureWay",
    "loanaAmount",
    "loanApplyDate",
    "assureType",
    "pledge",
    "refundWay",
    "refundTerm",
    "loanDueDate",
    "loanTerm",
    "refundMonth"
})
public class LoanInfo {

    @XmlElement(name = "LoanId")
    protected String loanId;
//    @XmlElement(name = "IsCarKeepPaper")
//    protected BigDecimal isCarKeepPaper;
    @XmlElement(name = "AssureWay")
    protected String assureWay;
    @XmlElement(name = "LoanaAmount")
    protected BigDecimal loanaAmount;
    @XmlElement(name = "LoanApplyDate")
    @XmlSchemaType(name = "date")
    protected String loanApplyDate;
//    @XmlElement(name = "CarValue")
//    protected BigDecimal carValue;
//    @XmlElement(name = "TransferNum")
//    protected BigDecimal transferNum;
//    @XmlElement(name = "CarType")
//    protected BigDecimal carType;
//    @XmlElement(name = "AS_Fraud")
//    protected BigDecimal asFraud;
//    @XmlElement(name = "CarUsedYear")
//    protected BigDecimal carUsedYear;
//    @XmlElement(name = "IsProcedureCom")
//    protected BigDecimal isProcedureCom;
//    @XmlElement(name = "IsCarstatusNormal")
//    protected BigDecimal isCarstatusNormal;
//    @XmlElement(name = "CarQuality")
//    protected BigDecimal carQuality;
    @XmlElement(name = "AssureType")
    protected BigDecimal assureType;
//    @XmlElement(name = "House_ES")
//    protected BigDecimal houseES;
//    @XmlElement(name = "HouseUsedYear")
//    protected BigDecimal houseUsedYear;
//    @XmlElement(name = "House_City")
//    protected String houseCity;
//    @XmlElement(name = "House_CityLevel")
//    protected BigDecimal houseCityLevel;
//    @XmlElement(name = "House_Use")
//    protected BigDecimal houseUse;
//    @XmlElement(name = "Mortgage_Type")
//    protected BigDecimal mortgageType;
    @XmlElement(name = "Pledge")
    protected BigDecimal pledge;
//    @XmlElement(name = "IsHouseOnly")
//    protected BigDecimal isHouseOnly;
//    @XmlElement(name = "IsDispute")
//    protected BigDecimal isDispute;
//    @XmlElement(name = "IsHouseKeepPaper")
//    protected BigDecimal isHouseKeepPaper;
//    @XmlElement(name = "HouseMortgage_Type")
//    protected BigDecimal houseMortgageType;
//    @XmlElement(name = "IsQueryFiles")
//    protected BigDecimal isQueryFiles;
    @XmlElement(name = "Refund_Way")
    protected BigDecimal refundWay;
    @XmlElement(name = "Refund_Term")
    protected BigDecimal refundTerm;
    @XmlElement(name = "LoanDueDate")
    @XmlSchemaType(name = "date")
    protected String loanDueDate;
    @XmlElement(name = "Loan_term")
    protected BigDecimal loanTerm;
//    @XmlElement(name = "IsTransfRec")
//    protected BigDecimal isTransfRec;
//    @XmlElement(name = "DueDispos")
//    protected BigDecimal dueDispos;
    @XmlElement(name = "Refund_Month")
    protected BigDecimal refundMonth;
	public String getLoanId() {
		return loanId;
	}
	public void setLoanId(String loanId) {
		this.loanId = loanId;
	}
	public String getAssureWay() {
		return assureWay;
	}
	public void setAssureWay(String assureWay) {
		this.assureWay = assureWay;
	}
	public BigDecimal getLoanaAmount() {
		return loanaAmount;
	}
	public void setLoanaAmount(BigDecimal loanaAmount) {
		this.loanaAmount = loanaAmount;
	}
	
	public String getLoanApplyDate() {
		return loanApplyDate;
	}
	public void setLoanApplyDate(String loanApplyDate) {
		this.loanApplyDate = loanApplyDate;
	}
	public BigDecimal getAssureType() {
		return assureType;
	}
	public void setAssureType(BigDecimal assureType) {
		this.assureType = assureType;
	}
	public BigDecimal getPledge() {
		return pledge;
	}
	public void setPledge(BigDecimal pledge) {
		this.pledge = pledge;
	}
	public BigDecimal getRefundWay() {
		return refundWay;
	}
	public void setRefundWay(BigDecimal refundWay) {
		this.refundWay = refundWay;
	}

	public BigDecimal getRefundTerm() {
		return refundTerm;
	}
	public void setRefundTerm(BigDecimal refundTerm) {
		this.refundTerm = refundTerm;
	}
	public String getLoanDueDate() {
		return loanDueDate;
	}
	public void setLoanDueDate(String loanDueDate) {
		this.loanDueDate = loanDueDate;
	}
	public BigDecimal getLoanTerm() {
		return loanTerm;
	}
	public void setLoanTerm(BigDecimal loanTerm) {
		this.loanTerm = loanTerm;
	}
	public BigDecimal getRefundMonth() {
		return refundMonth;
	}
	public void setRefundMonth(BigDecimal refundMonth) {
		this.refundMonth = refundMonth;
	}

	
}
