//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 06:41:27 PM CST 
//


package com.resoft.outinterface.cn.com.experian.entry.request.body;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PBOC_AppInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PBOC_AppInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="PBOC_App_RCTime" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PBOC_App_QueryTime" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_Loan_Override_amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_Loan_CL_status" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_Loan_WS" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_OfficePhone" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_DC_userate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_Worst_FC" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_Worst_FC_Foreign" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_MortgageNum" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_Query_PQnum" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_Query_Pynum" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_MAXDPD_CL_l12m" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_SELF_Query_L12m" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_AppQueryNum_L12m" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_SELF_Query_L1m" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_AppQueryNum_L1m" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_SELF_Query_L3m" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_AppQueryNum_L3m" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_SELF_Query_L6m" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_AppQueryyNum_L6m" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_Total_CL" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_SLoan_CL_status" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_SDC_CL_status" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_Worst_FC_OL" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_MobilePhone" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_ED_APPQuery_L12m" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_ED_APPQuery_L1m" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_ED_APPQuery_L3m" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_ED_APPQuery_L6m" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_DC_Override_amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_DC_CL_status" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_DC_Amount_Rate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_DC_WS" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_CH_Month" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_Query_Mnum" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_DueAmount_Loan_Month" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PBOC_App_CL_Maxnum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PBOC_App_LateDueLAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_App_LateDueTime" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PBOC_App_IsHistory_Loan" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PBOC_AppInfo", propOrder = {
    "pbocAppRCTime",
    "pbocAppQueryTime",
    "pbocAppLoanOverrideAmount",
    "pbocAppLoanCLStatus",
    "pbocAppIsWhite",
    "pbocAppLoanWS",
    "pbocAppOfficePhone",
    "pbocAppDCUserate",
    "pbocAppWorstFC",
    "pbocAppWorstFCForeign",
    "pbocAppMortgageNum",
    "pbocAppQueryPQnum",
    "pbocAppQueryPynum",
    "pbocAppMAXDPDCLL12M",
    "pbocAppSELFQueryL12M",
    "pbocAppAppQueryNumL12M",
    "pbocAppSELFQueryL1M",
    "pbocAppAppQueryNumL1M",
    "pbocAppSELFQueryL3M",
    "pbocAppAppQueryNumL3M",
    "pbocAppSELFQueryL6M",
    "pbocAppAppQueryyNumL6M",
    "pbocAppTotalCL",
    "pbocAppSLoanCLStatus",
    "pbocAppSDCCLStatus",
    "pbocAppWorstFCOL",
    "pbocAppSWorstFCOL",
    "pbocAppSDCOverrideAmount",
    "pbocAppMobilePhone",
    "pbocAppEDAPPQueryL12M",
    "pbocAppEDAPPQueryL1M",
    "pbocAppEDAPPQueryL3M",
    "pbocAppEDAPPQueryL6M",
    "pbocAppDCOverrideAmount",
    "pbocAppDCCLStatus",
    "pbocAppDCAmountRate",
    "pbocAppDCWS",
    "pbocAppCHMonth",
    "pbocAppQueryMnum",
    "pbocAppDueAmountLoanMonth",
    "pbocAppCLMaxnum",
    "pbocAppLateDueLAmount",
    "pbocAppLateDueTime",
    "pbocAppIsHistoryLoan",
    "pbocAppLoanNum",
    "pbocAppDCNum",
    "pbocAppForeignNum",
    "pbocAppIsHavePL"
})
public class PBOCAppInfo {

    @XmlElement(name = "PBOC_App_RCTime")
    @XmlSchemaType(name = "date")
    protected String pbocAppRCTime;
    @XmlElement(name = "PBOC_App_QueryTime")
    protected BigDecimal pbocAppQueryTime;
    @XmlElement(name = "PBOC_App_Loan_Override_amount")
    protected BigDecimal pbocAppLoanOverrideAmount;
    @XmlElement(name = "PBOC_App_Loan_CL_status")
    protected BigDecimal pbocAppLoanCLStatus;
    @XmlElement(name = "PBOC_App_IsWhite")
    protected BigDecimal pbocAppIsWhite;
    @XmlElement(name = "PBOC_App_Loan_WS")
    protected BigDecimal pbocAppLoanWS;
    @XmlElement(name = "PBOC_App_OfficePhone")
    protected BigDecimal pbocAppOfficePhone;
    @XmlElement(name = "PBOC_App_DC_userate")
    protected BigDecimal pbocAppDCUserate;
    @XmlElement(name = "PBOC_App_Worst_FC")
    protected BigDecimal pbocAppWorstFC;
    @XmlElement(name = "PBOC_App_Worst_FC_Foreign")
    protected BigDecimal pbocAppWorstFCForeign;
    @XmlElement(name = "PBOC_App_MortgageNum")
    protected BigDecimal pbocAppMortgageNum;
    @XmlElement(name = "PBOC_App_Query_PQnum")
    protected BigDecimal pbocAppQueryPQnum;
    @XmlElement(name = "PBOC_App_Query_Pynum")
    protected BigDecimal pbocAppQueryPynum;
    @XmlElement(name = "PBOC_App_MAXDPD_CL_l12m")
    protected BigDecimal pbocAppMAXDPDCLL12M;
    @XmlElement(name = "PBOC_App_SELF_Query_L12m")
    protected BigDecimal pbocAppSELFQueryL12M;
    @XmlElement(name = "PBOC_App_AppQueryNum_L12m")
    protected BigDecimal pbocAppAppQueryNumL12M;
    @XmlElement(name = "PBOC_App_SELF_Query_L1m")
    protected BigDecimal pbocAppSELFQueryL1M;
    @XmlElement(name = "PBOC_App_AppQueryNum_L1m")
    protected BigDecimal pbocAppAppQueryNumL1M;
    @XmlElement(name = "PBOC_App_SELF_Query_L3m")
    protected BigDecimal pbocAppSELFQueryL3M;
    @XmlElement(name = "PBOC_App_AppQueryNum_L3m")
    protected BigDecimal pbocAppAppQueryNumL3M;
    @XmlElement(name = "PBOC_App_SELF_Query_L6m")
    protected BigDecimal pbocAppSELFQueryL6M;
    @XmlElement(name = "PBOC_App_AppQueryyNum_L6m")
    protected BigDecimal pbocAppAppQueryyNumL6M;
    @XmlElement(name = "PBOC_App_Total_CL")
    protected BigDecimal pbocAppTotalCL;
    @XmlElement(name = "PBOC_App_SLoan_CL_status")
    protected BigDecimal pbocAppSLoanCLStatus;
    @XmlElement(name = "PBOC_App_SDC_CL_status")
    protected BigDecimal pbocAppSDCCLStatus;
    @XmlElement(name = "PBOC_App_Worst_FC_OL")
    protected BigDecimal pbocAppWorstFCOL;
    @XmlElement(name = "PBOC_App_SWorst_FC_OL")
    protected BigDecimal pbocAppSWorstFCOL;
    @XmlElement(name = "PBOC_App_SDC_Override_amount")
    protected BigDecimal pbocAppSDCOverrideAmount;
    @XmlElement(name = "PBOC_App_MobilePhone")
    protected BigDecimal pbocAppMobilePhone;
    @XmlElement(name = "PBOC_App_ED_APPQuery_L12m")
    protected BigDecimal pbocAppEDAPPQueryL12M;
    @XmlElement(name = "PBOC_App_ED_APPQuery_L1m")
    protected BigDecimal pbocAppEDAPPQueryL1M;
    @XmlElement(name = "PBOC_App_ED_APPQuery_L3m")
    protected BigDecimal pbocAppEDAPPQueryL3M;
    @XmlElement(name = "PBOC_App_ED_APPQuery_L6m")
    protected BigDecimal pbocAppEDAPPQueryL6M;
    @XmlElement(name = "PBOC_App_DC_Override_amount")
    protected BigDecimal pbocAppDCOverrideAmount;
    @XmlElement(name = "PBOC_App_DC_CL_status")
    protected BigDecimal pbocAppDCCLStatus;
    @XmlElement(name = "PBOC_App_DC_Amount_Rate")
    protected BigDecimal pbocAppDCAmountRate;
    @XmlElement(name = "PBOC_App_DC_WS")
    protected BigDecimal pbocAppDCWS;
    @XmlElement(name = "PBOC_App_CH_Month")
    protected BigDecimal pbocAppCHMonth;
    @XmlElement(name = "PBOC_App_Query_Mnum")
    protected BigDecimal pbocAppQueryMnum;
    @XmlElement(name = "PBOC_App_DueAmount_Loan_Month")
    protected BigDecimal pbocAppDueAmountLoanMonth;
    @XmlElement(name = "PBOC_App_CL_Maxnum")
    protected BigDecimal pbocAppCLMaxnum;
    @XmlElement(name = "PBOC_App_LateDueLAmount")
    protected BigDecimal pbocAppLateDueLAmount;
    @XmlElement(name = "PBOC_App_LateDueTime")
    @XmlSchemaType(name = "date")
    protected String pbocAppLateDueTime;
    @XmlElement(name = "PBOC_App_IsHistory_Loan")
    protected BigDecimal pbocAppIsHistoryLoan;
    @XmlElement(name = "PBOC_App_loan_num")
    protected BigDecimal pbocAppLoanNum;
    @XmlElement(name = "PBOC_App_DC_num")
    protected BigDecimal pbocAppDCNum;
    @XmlElement(name = "PBOC_App_Foreign_num")
    protected BigDecimal pbocAppForeignNum;
    @XmlElement(name = "PBOC_App_IsHavePL")
    protected BigDecimal pbocAppIsHavePL;
    

   

    /**
     * Gets the value of the pbocAppQueryTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppQueryTime() {
        return pbocAppQueryTime;
    }

    /**
     * Sets the value of the pbocAppQueryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppQueryTime(BigDecimal value) {
        this.pbocAppQueryTime = value;
    }

    /**
     * Gets the value of the pbocAppLoanCLStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppLoanCLStatus() {
        return pbocAppLoanCLStatus;
    }

    /**
     * Sets the value of the pbocAppLoanCLStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppLoanCLStatus(BigDecimal value) {
        this.pbocAppLoanCLStatus = value;
    }

    /**
     * Gets the value of the pbocAppLoanWS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppLoanWS() {
        return pbocAppLoanWS;
    }

    /**
     * Sets the value of the pbocAppLoanWS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppLoanWS(BigDecimal value) {
        this.pbocAppLoanWS = value;
    }

    /**
     * Gets the value of the pbocAppOfficePhone property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppOfficePhone() {
        return pbocAppOfficePhone;
    }

    /**
     * Sets the value of the pbocAppOfficePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppOfficePhone(BigDecimal value) {
        this.pbocAppOfficePhone = value;
    }

    /**
     * Gets the value of the pbocAppDCUserate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppDCUserate() {
        return pbocAppDCUserate;
    }

    /**
     * Sets the value of the pbocAppDCUserate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppDCUserate(BigDecimal value) {
        this.pbocAppDCUserate = value;
    }

    /**
     * Gets the value of the pbocAppWorstFC property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppWorstFC() {
        return pbocAppWorstFC;
    }

    /**
     * Sets the value of the pbocAppWorstFC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppWorstFC(BigDecimal value) {
        this.pbocAppWorstFC = value;
    }

    /**
     * Gets the value of the pbocAppWorstFCForeign property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppWorstFCForeign() {
        return pbocAppWorstFCForeign;
    }

    /**
     * Sets the value of the pbocAppWorstFCForeign property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppWorstFCForeign(BigDecimal value) {
        this.pbocAppWorstFCForeign = value;
    }

    /**
     * Gets the value of the pbocAppMortgageNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppMortgageNum() {
        return pbocAppMortgageNum;
    }

    /**
     * Sets the value of the pbocAppMortgageNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppMortgageNum(BigDecimal value) {
        this.pbocAppMortgageNum = value;
    }

    /**
     * Gets the value of the pbocAppQueryPQnum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppQueryPQnum() {
        return pbocAppQueryPQnum;
    }

    /**
     * Sets the value of the pbocAppQueryPQnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppQueryPQnum(BigDecimal value) {
        this.pbocAppQueryPQnum = value;
    }

    /**
     * Gets the value of the pbocAppQueryPynum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppQueryPynum() {
        return pbocAppQueryPynum;
    }

    /**
     * Sets the value of the pbocAppQueryPynum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppQueryPynum(BigDecimal value) {
        this.pbocAppQueryPynum = value;
    }

    /**
     * Gets the value of the pbocAppMAXDPDCLL12M property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppMAXDPDCLL12M() {
        return pbocAppMAXDPDCLL12M;
    }

    /**
     * Sets the value of the pbocAppMAXDPDCLL12M property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppMAXDPDCLL12M(BigDecimal value) {
        this.pbocAppMAXDPDCLL12M = value;
    }

    /**
     * Gets the value of the pbocAppSELFQueryL12M property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppSELFQueryL12M() {
        return pbocAppSELFQueryL12M;
    }

    /**
     * Sets the value of the pbocAppSELFQueryL12M property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppSELFQueryL12M(BigDecimal value) {
        this.pbocAppSELFQueryL12M = value;
    }

    /**
     * Gets the value of the pbocAppAppQueryNumL12M property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppAppQueryNumL12M() {
        return pbocAppAppQueryNumL12M;
    }

    /**
     * Sets the value of the pbocAppAppQueryNumL12M property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppAppQueryNumL12M(BigDecimal value) {
        this.pbocAppAppQueryNumL12M = value;
    }

    /**
     * Gets the value of the pbocAppSELFQueryL1M property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppSELFQueryL1M() {
        return pbocAppSELFQueryL1M;
    }

    /**
     * Sets the value of the pbocAppSELFQueryL1M property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppSELFQueryL1M(BigDecimal value) {
        this.pbocAppSELFQueryL1M = value;
    }

    /**
     * Gets the value of the pbocAppAppQueryNumL1M property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppAppQueryNumL1M() {
        return pbocAppAppQueryNumL1M;
    }

    /**
     * Sets the value of the pbocAppAppQueryNumL1M property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppAppQueryNumL1M(BigDecimal value) {
        this.pbocAppAppQueryNumL1M = value;
    }

    /**
     * Gets the value of the pbocAppSELFQueryL3M property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppSELFQueryL3M() {
        return pbocAppSELFQueryL3M;
    }

    /**
     * Sets the value of the pbocAppSELFQueryL3M property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppSELFQueryL3M(BigDecimal value) {
        this.pbocAppSELFQueryL3M = value;
    }

    /**
     * Gets the value of the pbocAppAppQueryNumL3M property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppAppQueryNumL3M() {
        return pbocAppAppQueryNumL3M;
    }

    /**
     * Sets the value of the pbocAppAppQueryNumL3M property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppAppQueryNumL3M(BigDecimal value) {
        this.pbocAppAppQueryNumL3M = value;
    }

    /**
     * Gets the value of the pbocAppSELFQueryL6M property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppSELFQueryL6M() {
        return pbocAppSELFQueryL6M;
    }

    /**
     * Sets the value of the pbocAppSELFQueryL6M property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppSELFQueryL6M(BigDecimal value) {
        this.pbocAppSELFQueryL6M = value;
    }

    /**
     * Gets the value of the pbocAppAppQueryyNumL6M property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppAppQueryyNumL6M() {
        return pbocAppAppQueryyNumL6M;
    }

    /**
     * Sets the value of the pbocAppAppQueryyNumL6M property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppAppQueryyNumL6M(BigDecimal value) {
        this.pbocAppAppQueryyNumL6M = value;
    }

    /**
     * Gets the value of the pbocAppTotalCL property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppTotalCL() {
        return pbocAppTotalCL;
    }

    /**
     * Sets the value of the pbocAppTotalCL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppTotalCL(BigDecimal value) {
        this.pbocAppTotalCL = value;
    }

    /**
     * Gets the value of the pbocAppSLoanCLStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppSLoanCLStatus() {
        return pbocAppSLoanCLStatus;
    }

    /**
     * Sets the value of the pbocAppSLoanCLStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppSLoanCLStatus(BigDecimal value) {
        this.pbocAppSLoanCLStatus = value;
    }


	/**
     * Gets the value of the pbocAppSDCCLStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppSDCCLStatus() {
        return pbocAppSDCCLStatus;
    }

    /**
     * Sets the value of the pbocAppSDCCLStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppSDCCLStatus(BigDecimal value) {
        this.pbocAppSDCCLStatus = value;
    }

    /**
     * Gets the value of the pbocAppWorstFCOL property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppWorstFCOL() {
        return pbocAppWorstFCOL;
    }

    /**
     * Sets the value of the pbocAppWorstFCOL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppWorstFCOL(BigDecimal value) {
        this.pbocAppWorstFCOL = value;
    }

    /**
     * Gets the value of the pbocAppMobilePhone property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppMobilePhone() {
        return pbocAppMobilePhone;
    }

    /**
     * Sets the value of the pbocAppMobilePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppMobilePhone(BigDecimal value) {
        this.pbocAppMobilePhone = value;
    }

    /**
     * Gets the value of the pbocAppEDAPPQueryL12M property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppEDAPPQueryL12M() {
        return pbocAppEDAPPQueryL12M;
    }

    /**
     * Sets the value of the pbocAppEDAPPQueryL12M property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppEDAPPQueryL12M(BigDecimal value) {
        this.pbocAppEDAPPQueryL12M = value;
    }

    /**
     * Gets the value of the pbocAppEDAPPQueryL1M property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppEDAPPQueryL1M() {
        return pbocAppEDAPPQueryL1M;
    }

    /**
     * Sets the value of the pbocAppEDAPPQueryL1M property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppEDAPPQueryL1M(BigDecimal value) {
        this.pbocAppEDAPPQueryL1M = value;
    }

    /**
     * Gets the value of the pbocAppEDAPPQueryL3M property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppEDAPPQueryL3M() {
        return pbocAppEDAPPQueryL3M;
    }

    /**
     * Sets the value of the pbocAppEDAPPQueryL3M property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppEDAPPQueryL3M(BigDecimal value) {
        this.pbocAppEDAPPQueryL3M = value;
    }

    /**
     * Gets the value of the pbocAppEDAPPQueryL6M property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppEDAPPQueryL6M() {
        return pbocAppEDAPPQueryL6M;
    }

    /**
     * Sets the value of the pbocAppEDAPPQueryL6M property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppEDAPPQueryL6M(BigDecimal value) {
        this.pbocAppEDAPPQueryL6M = value;
    }

    /**
     * Gets the value of the pbocAppDCOverrideAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppDCOverrideAmount() {
        return pbocAppDCOverrideAmount;
    }

    /**
     * Sets the value of the pbocAppDCOverrideAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppDCOverrideAmount(BigDecimal value) {
        this.pbocAppDCOverrideAmount = value;
    }

    /**
     * Gets the value of the pbocAppDCCLStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppDCCLStatus() {
        return pbocAppDCCLStatus;
    }

    /**
     * Sets the value of the pbocAppDCCLStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppDCCLStatus(BigDecimal value) {
        this.pbocAppDCCLStatus = value;
    }

    /**
     * Gets the value of the pbocAppDCAmountRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppDCAmountRate() {
        return pbocAppDCAmountRate;
    }

    /**
     * Sets the value of the pbocAppDCAmountRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppDCAmountRate(BigDecimal value) {
        this.pbocAppDCAmountRate = value;
    }

    /**
     * Gets the value of the pbocAppDCWS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppDCWS() {
        return pbocAppDCWS;
    }

    /**
     * Sets the value of the pbocAppDCWS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppDCWS(BigDecimal value) {
        this.pbocAppDCWS = value;
    }

    /**
     * Gets the value of the pbocAppCHMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppCHMonth() {
        return pbocAppCHMonth;
    }

    /**
     * Sets the value of the pbocAppCHMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppCHMonth(BigDecimal value) {
        this.pbocAppCHMonth = value;
    }

    /**
     * Gets the value of the pbocAppQueryMnum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppQueryMnum() {
        return pbocAppQueryMnum;
    }

    /**
     * Sets the value of the pbocAppQueryMnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppQueryMnum(BigDecimal value) {
        this.pbocAppQueryMnum = value;
    }

    /**
     * Gets the value of the pbocAppDueAmountLoanMonth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public BigDecimal getPBOCAppDueAmountLoanMonth() {
        return pbocAppDueAmountLoanMonth;
    }

    /**
     * Sets the value of the pbocAppDueAmountLoanMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPBOCAppDueAmountLoanMonth(BigDecimal value) {
        this.pbocAppDueAmountLoanMonth = value;
    }

    /**
     * Gets the value of the pbocAppCLMaxnum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public BigDecimal getPBOCAppCLMaxnum() {
        return pbocAppCLMaxnum;
    }

    /**
     * Sets the value of the pbocAppCLMaxnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPBOCAppCLMaxnum(BigDecimal value) {
        this.pbocAppCLMaxnum = value;
    }

    /**
     * Gets the value of the pbocAppLateDueLAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppLateDueLAmount() {
        return pbocAppLateDueLAmount;
    }

    /**
     * Sets the value of the pbocAppLateDueLAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppLateDueLAmount(BigDecimal value) {
        this.pbocAppLateDueLAmount = value;
    }

    

    /**
     * Gets the value of the pbocAppIsHistoryLoan property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCAppIsHistoryLoan() {
        return pbocAppIsHistoryLoan;
    }

    /**
     * Sets the value of the pbocAppIsHistoryLoan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCAppIsHistoryLoan(BigDecimal value) {
        this.pbocAppIsHistoryLoan = value;
    }

	

	public BigDecimal getPbocAppQueryTime() {
		return pbocAppQueryTime;
	}

	public void setPbocAppQueryTime(BigDecimal pbocAppQueryTime) {
		this.pbocAppQueryTime = pbocAppQueryTime;
	}

	public BigDecimal getPbocAppLoanOverrideAmount() {
		return pbocAppLoanOverrideAmount;
	}

	public void setPbocAppLoanOverrideAmount(BigDecimal pbocAppLoanOverrideAmount) {
		this.pbocAppLoanOverrideAmount = pbocAppLoanOverrideAmount;
	}

	public BigDecimal getPbocAppLoanCLStatus() {
		return pbocAppLoanCLStatus;
	}

	public void setPbocAppLoanCLStatus(BigDecimal pbocAppLoanCLStatus) {
		this.pbocAppLoanCLStatus = pbocAppLoanCLStatus;
	}

	public BigDecimal getPbocAppLoanWS() {
		return pbocAppLoanWS;
	}

	public void setPbocAppLoanWS(BigDecimal pbocAppLoanWS) {
		this.pbocAppLoanWS = pbocAppLoanWS;
	}

	public BigDecimal getPbocAppOfficePhone() {
		return pbocAppOfficePhone;
	}

	public void setPbocAppOfficePhone(BigDecimal pbocAppOfficePhone) {
		this.pbocAppOfficePhone = pbocAppOfficePhone;
	}

	public BigDecimal getPbocAppDCUserate() {
		return pbocAppDCUserate;
	}

	public void setPbocAppDCUserate(BigDecimal pbocAppDCUserate) {
		this.pbocAppDCUserate = pbocAppDCUserate;
	}

	public BigDecimal getPbocAppWorstFC() {
		return pbocAppWorstFC;
	}

	public void setPbocAppWorstFC(BigDecimal pbocAppWorstFC) {
		this.pbocAppWorstFC = pbocAppWorstFC;
	}

	public BigDecimal getPbocAppWorstFCForeign() {
		return pbocAppWorstFCForeign;
	}

	public void setPbocAppWorstFCForeign(BigDecimal pbocAppWorstFCForeign) {
		this.pbocAppWorstFCForeign = pbocAppWorstFCForeign;
	}

	public BigDecimal getPbocAppMortgageNum() {
		return pbocAppMortgageNum;
	}

	public void setPbocAppMortgageNum(BigDecimal pbocAppMortgageNum) {
		this.pbocAppMortgageNum = pbocAppMortgageNum;
	}

	public BigDecimal getPbocAppQueryPQnum() {
		return pbocAppQueryPQnum;
	}

	public void setPbocAppQueryPQnum(BigDecimal pbocAppQueryPQnum) {
		this.pbocAppQueryPQnum = pbocAppQueryPQnum;
	}

	public BigDecimal getPbocAppQueryPynum() {
		return pbocAppQueryPynum;
	}

	public void setPbocAppQueryPynum(BigDecimal pbocAppQueryPynum) {
		this.pbocAppQueryPynum = pbocAppQueryPynum;
	}

	public BigDecimal getPbocAppMAXDPDCLL12M() {
		return pbocAppMAXDPDCLL12M;
	}

	public void setPbocAppMAXDPDCLL12M(BigDecimal pbocAppMAXDPDCLL12M) {
		this.pbocAppMAXDPDCLL12M = pbocAppMAXDPDCLL12M;
	}

	public BigDecimal getPbocAppSELFQueryL12M() {
		return pbocAppSELFQueryL12M;
	}

	public void setPbocAppSELFQueryL12M(BigDecimal pbocAppSELFQueryL12M) {
		this.pbocAppSELFQueryL12M = pbocAppSELFQueryL12M;
	}

	public BigDecimal getPbocAppAppQueryNumL12M() {
		return pbocAppAppQueryNumL12M;
	}

	public void setPbocAppAppQueryNumL12M(BigDecimal pbocAppAppQueryNumL12M) {
		this.pbocAppAppQueryNumL12M = pbocAppAppQueryNumL12M;
	}

	public BigDecimal getPbocAppSELFQueryL1M() {
		return pbocAppSELFQueryL1M;
	}

	public void setPbocAppSELFQueryL1M(BigDecimal pbocAppSELFQueryL1M) {
		this.pbocAppSELFQueryL1M = pbocAppSELFQueryL1M;
	}

	public BigDecimal getPbocAppAppQueryNumL1M() {
		return pbocAppAppQueryNumL1M;
	}

	public void setPbocAppAppQueryNumL1M(BigDecimal pbocAppAppQueryNumL1M) {
		this.pbocAppAppQueryNumL1M = pbocAppAppQueryNumL1M;
	}

	public BigDecimal getPbocAppSELFQueryL3M() {
		return pbocAppSELFQueryL3M;
	}

	public void setPbocAppSELFQueryL3M(BigDecimal pbocAppSELFQueryL3M) {
		this.pbocAppSELFQueryL3M = pbocAppSELFQueryL3M;
	}

	public BigDecimal getPbocAppAppQueryNumL3M() {
		return pbocAppAppQueryNumL3M;
	}

	public void setPbocAppAppQueryNumL3M(BigDecimal pbocAppAppQueryNumL3M) {
		this.pbocAppAppQueryNumL3M = pbocAppAppQueryNumL3M;
	}

	public BigDecimal getPbocAppSELFQueryL6M() {
		return pbocAppSELFQueryL6M;
	}

	public void setPbocAppSELFQueryL6M(BigDecimal pbocAppSELFQueryL6M) {
		this.pbocAppSELFQueryL6M = pbocAppSELFQueryL6M;
	}

	public BigDecimal getPbocAppAppQueryyNumL6M() {
		return pbocAppAppQueryyNumL6M;
	}

	public void setPbocAppAppQueryyNumL6M(BigDecimal pbocAppAppQueryyNumL6M) {
		this.pbocAppAppQueryyNumL6M = pbocAppAppQueryyNumL6M;
	}

	public BigDecimal getPbocAppTotalCL() {
		return pbocAppTotalCL;
	}

	public void setPbocAppTotalCL(BigDecimal pbocAppTotalCL) {
		this.pbocAppTotalCL = pbocAppTotalCL;
	}

	public BigDecimal getPbocAppSLoanCLStatus() {
		return pbocAppSLoanCLStatus;
	}

	public void setPbocAppSLoanCLStatus(BigDecimal pbocAppSLoanCLStatus) {
		this.pbocAppSLoanCLStatus = pbocAppSLoanCLStatus;
	}

	public BigDecimal getPbocAppSDCCLStatus() {
		return pbocAppSDCCLStatus;
	}

	public void setPbocAppSDCCLStatus(BigDecimal pbocAppSDCCLStatus) {
		this.pbocAppSDCCLStatus = pbocAppSDCCLStatus;
	}

	public BigDecimal getPbocAppWorstFCOL() {
		return pbocAppWorstFCOL;
	}

	public void setPbocAppWorstFCOL(BigDecimal pbocAppWorstFCOL) {
		this.pbocAppWorstFCOL = pbocAppWorstFCOL;
	}

	public BigDecimal getPbocAppMobilePhone() {
		return pbocAppMobilePhone;
	}

	public void setPbocAppMobilePhone(BigDecimal pbocAppMobilePhone) {
		this.pbocAppMobilePhone = pbocAppMobilePhone;
	}

	public BigDecimal getPbocAppEDAPPQueryL12M() {
		return pbocAppEDAPPQueryL12M;
	}

	public void setPbocAppEDAPPQueryL12M(BigDecimal pbocAppEDAPPQueryL12M) {
		this.pbocAppEDAPPQueryL12M = pbocAppEDAPPQueryL12M;
	}

	public BigDecimal getPbocAppEDAPPQueryL1M() {
		return pbocAppEDAPPQueryL1M;
	}

	public void setPbocAppEDAPPQueryL1M(BigDecimal pbocAppEDAPPQueryL1M) {
		this.pbocAppEDAPPQueryL1M = pbocAppEDAPPQueryL1M;
	}

	public BigDecimal getPbocAppEDAPPQueryL3M() {
		return pbocAppEDAPPQueryL3M;
	}

	public void setPbocAppEDAPPQueryL3M(BigDecimal pbocAppEDAPPQueryL3M) {
		this.pbocAppEDAPPQueryL3M = pbocAppEDAPPQueryL3M;
	}

	public BigDecimal getPbocAppEDAPPQueryL6M() {
		return pbocAppEDAPPQueryL6M;
	}

	public void setPbocAppEDAPPQueryL6M(BigDecimal pbocAppEDAPPQueryL6M) {
		this.pbocAppEDAPPQueryL6M = pbocAppEDAPPQueryL6M;
	}

	public BigDecimal getPbocAppDCOverrideAmount() {
		return pbocAppDCOverrideAmount;
	}

	public void setPbocAppDCOverrideAmount(BigDecimal pbocAppDCOverrideAmount) {
		this.pbocAppDCOverrideAmount = pbocAppDCOverrideAmount;
	}

	public BigDecimal getPbocAppDCCLStatus() {
		return pbocAppDCCLStatus;
	}

	public void setPbocAppDCCLStatus(BigDecimal pbocAppDCCLStatus) {
		this.pbocAppDCCLStatus = pbocAppDCCLStatus;
	}

	public BigDecimal getPbocAppDCAmountRate() {
		return pbocAppDCAmountRate;
	}

	public void setPbocAppDCAmountRate(BigDecimal pbocAppDCAmountRate) {
		this.pbocAppDCAmountRate = pbocAppDCAmountRate;
	}

	public BigDecimal getPbocAppDCWS() {
		return pbocAppDCWS;
	}

	public void setPbocAppDCWS(BigDecimal pbocAppDCWS) {
		this.pbocAppDCWS = pbocAppDCWS;
	}

	public BigDecimal getPbocAppCHMonth() {
		return pbocAppCHMonth;
	}

	public void setPbocAppCHMonth(BigDecimal pbocAppCHMonth) {
		this.pbocAppCHMonth = pbocAppCHMonth;
	}

	public BigDecimal getPbocAppQueryMnum() {
		return pbocAppQueryMnum;
	}

	public void setPbocAppQueryMnum(BigDecimal pbocAppQueryMnum) {
		this.pbocAppQueryMnum = pbocAppQueryMnum;
	}

	public BigDecimal getPbocAppDueAmountLoanMonth() {
		return pbocAppDueAmountLoanMonth;
	}

	public void setPbocAppDueAmountLoanMonth(BigDecimal pbocAppDueAmountLoanMonth) {
		this.pbocAppDueAmountLoanMonth = pbocAppDueAmountLoanMonth;
	}

	public BigDecimal getPbocAppCLMaxnum() {
		return pbocAppCLMaxnum;
	}

	public void setPbocAppCLMaxnum(BigDecimal pbocAppCLMaxnum) {
		this.pbocAppCLMaxnum = pbocAppCLMaxnum;
	}

	public BigDecimal getPbocAppLateDueLAmount() {
		return pbocAppLateDueLAmount;
	}

	public void setPbocAppLateDueLAmount(BigDecimal pbocAppLateDueLAmount) {
		this.pbocAppLateDueLAmount = pbocAppLateDueLAmount;
	}

	

	public BigDecimal getPbocAppIsHistoryLoan() {
		return pbocAppIsHistoryLoan;
	}

	public void setPbocAppIsHistoryLoan(BigDecimal pbocAppIsHistoryLoan) {
		this.pbocAppIsHistoryLoan = pbocAppIsHistoryLoan;
	}

	public BigDecimal getPbocAppLoanNum() {
		return pbocAppLoanNum;
	}

	public void setPbocAppLoanNum(BigDecimal pbocAppLoanNum) {
		this.pbocAppLoanNum = pbocAppLoanNum;
	}

	public BigDecimal getPbocAppDCNum() {
		return pbocAppDCNum;
	}

	public void setPbocAppDCNum(BigDecimal pbocAppDCNum) {
		this.pbocAppDCNum = pbocAppDCNum;
	}

	public BigDecimal getPbocAppForeignNum() {
		return pbocAppForeignNum;
	}

	public void setPbocAppForeignNum(BigDecimal pbocAppForeignNum) {
		this.pbocAppForeignNum = pbocAppForeignNum;
	}

	public BigDecimal getPbocAppIsHavePL() {
		return pbocAppIsHavePL;
	}

	public void setPbocAppIsHavePL(BigDecimal pbocAppIsHavePL) {
		this.pbocAppIsHavePL = pbocAppIsHavePL;
	}

	public String getPbocAppRCTime() {
		return pbocAppRCTime;
	}

	public void setPbocAppRCTime(String pbocAppRCTime) {
		this.pbocAppRCTime = pbocAppRCTime;
	}

	public String getPbocAppLateDueTime() {
		return pbocAppLateDueTime;
	}

	public void setPbocAppLateDueTime(String pbocAppLateDueTime) {
		this.pbocAppLateDueTime = pbocAppLateDueTime;
	}

	public BigDecimal getPbocAppIsWhite() {
		return pbocAppIsWhite;
	}

	public void setPbocAppIsWhite(BigDecimal pbocAppIsWhite) {
		this.pbocAppIsWhite = pbocAppIsWhite;
	}

	public BigDecimal getPbocAppSWorstFCOL() {
		return pbocAppSWorstFCOL;
	}

	public void setPbocAppSWorstFCOL(BigDecimal pbocAppSWorstFCOL) {
		this.pbocAppSWorstFCOL = pbocAppSWorstFCOL;
	}

	public BigDecimal getPbocAppSDCOverrideAmount() {
		return pbocAppSDCOverrideAmount;
	}

	public void setPbocAppSDCOverrideAmount(BigDecimal pbocAppSDCOverrideAmount) {
		this.pbocAppSDCOverrideAmount = pbocAppSDCOverrideAmount;
	}
	
}
