//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 06:41:27 PM CST 
//


package com.resoft.outinterface.cn.com.experian.entry.request.body;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PBOC_CoAppInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PBOC_CoAppInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="PBOC_CoApp_RCTime" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_QueryTime" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_Loan_CL_status" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_Worst_FC" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_PhoneBill_Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_Phonebill_Month" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_Worst_FC_Foreign" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_Query_PQnum" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_Query_PYnum" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_total_CL" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_Loanl50_Due" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_Loanh50_Due" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_UCloseAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_IsInvolved" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_MobilPhoone" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_DC_CL_status" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_DC_Worst_FC" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_DC_AmountRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_DC_Worst_state" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_CH_Month" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_Query_Mnum" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_max_CL" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_LateDueLAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_LateDueLTime" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PBOC_CoApp_IsHistory_Loan" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PBOC_CoAppInfo", propOrder = {
    "pbocCoAppRCTime",
    "pbocCoAppQueryTime",
    "pbocCoAppLoanCLStatus",
    "pbocCoAppWorstFC",
    "pbocCoAppPhoneBillAmount",
    "pbocCoAppPhonebillMonth",
    "pbocCoAppWorstFCForeign",
    "pbocCoAppQueryPQnum",
    "pbocCoAppQueryPYnum",
    "pbocCoAppTotalCL",
    "pbocCoAppLoanl50Due",
    "pbocCoAppLoanh50Due",
    "pbocCoAppUCloseAmount",
    "pbocCoAppIsInvolved",
    "pbocCoAppMobilPhoone",
    "pbocCoAppDCCLStatus",
    "pbocCoAppDCWorstFC",
    "pbocCoAppDCAmountRate",
    "pbocCoAppDCWorstState",
    "pbocCoAppCHMonth",
    "pbocCoAppQueryMnum",
    "pbocCoAppMaxCL",
    "pbocCoAppLateDueLAmount",
    "pbocCoAppLateDueLTime",
    "pbocCoAppIsHistoryLoan",
    "pbocCoAppLoanNum",
    "pbocCoAppDCNum",
    "pbocCoAppForeignNum",
    "pbocCoAppIsHavePL"
})
public class PBOCCoAppInfo {

    @XmlElement(name = "PBOC_CoApp_RCTime")
    @XmlSchemaType(name = "date")
    protected String pbocCoAppRCTime;
    @XmlElement(name = "PBOC_CoApp_QueryTime")
    protected BigDecimal pbocCoAppQueryTime;
    @XmlElement(name = "PBOC_CoApp_Loan_CL_status")
    protected BigDecimal pbocCoAppLoanCLStatus;
    @XmlElement(name = "PBOC_CoApp_Worst_FC")
    protected BigDecimal pbocCoAppWorstFC;
    @XmlElement(name = "PBOC_CoApp_PhoneBill_Amount")
    protected BigDecimal pbocCoAppPhoneBillAmount;
    @XmlElement(name = "PBOC_CoApp_Phonebill_Month")
    protected BigDecimal pbocCoAppPhonebillMonth;
    @XmlElement(name = "PBOC_CoApp_Worst_FC_Foreign")
    protected BigDecimal pbocCoAppWorstFCForeign;
    @XmlElement(name = "PBOC_CoApp_Query_PQnum")
    protected BigDecimal pbocCoAppQueryPQnum;
    @XmlElement(name = "PBOC_CoApp_Query_PYnum")
    protected BigDecimal pbocCoAppQueryPYnum;
    @XmlElement(name = "PBOC_CoApp_total_CL")
    protected BigDecimal pbocCoAppTotalCL;
    @XmlElement(name = "PBOC_CoApp_Loanl50_Due")
    @XmlSchemaType(name = "date")
    protected String pbocCoAppLoanl50Due;
    @XmlElement(name = "PBOC_CoApp_Loanh50_Due")
    @XmlSchemaType(name = "date")
    protected String pbocCoAppLoanh50Due;
    @XmlElement(name = "PBOC_CoApp_UCloseAmount")
    protected BigDecimal pbocCoAppUCloseAmount;
    @XmlElement(name = "PBOC_CoApp_IsInvolved")
    protected BigDecimal pbocCoAppIsInvolved;
    @XmlElement(name = "PBOC_CoApp_MobilPhoone")
    protected BigDecimal pbocCoAppMobilPhoone;
    @XmlElement(name = "PBOC_CoApp_DC_CL_status")
    protected BigDecimal pbocCoAppDCCLStatus;
    @XmlElement(name = "PBOC_CoApp_DC_Worst_FC")
    protected BigDecimal pbocCoAppDCWorstFC;
    @XmlElement(name = "PBOC_CoApp_DC_AmountRate")
    protected BigDecimal pbocCoAppDCAmountRate;
    @XmlElement(name = "PBOC_CoApp_DC_Worst_state")
    protected BigDecimal pbocCoAppDCWorstState;
    @XmlElement(name = "PBOC_CoApp_CH_Month")
    protected BigDecimal pbocCoAppCHMonth;
    @XmlElement(name = "PBOC_CoApp_Query_Mnum")
    protected BigDecimal pbocCoAppQueryMnum;
    @XmlElement(name = "PBOC_CoApp_max_CL")
    protected BigDecimal pbocCoAppMaxCL;
    @XmlElement(name = "PBOC_CoApp_LateDueLAmount")
    protected String pbocCoAppLateDueLAmount;
    @XmlElement(name = "PBOC_CoApp_LateDueLTime")
    @XmlSchemaType(name = "date")
    protected String pbocCoAppLateDueLTime;
    @XmlElement(name = "PBOC_CoApp_IsHistory_Loan")
    protected BigDecimal pbocCoAppIsHistoryLoan;
    @XmlElement(name = "PBOC_CoApp_loan_num")
    protected BigDecimal pbocCoAppLoanNum;
    @XmlElement(name = "PBOC_CoApp_DC_num")
    protected BigDecimal pbocCoAppDCNum;
    @XmlElement(name = "PBOC_CoApp_Foreign_num")
    protected BigDecimal pbocCoAppForeignNum;
    @XmlElement(name = "PBOC_CoApp_IsHavePL")
    protected BigDecimal pbocCoAppIsHavePL;
   


    /**
     * Gets the value of the pbocCoAppQueryTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppQueryTime() {
        return pbocCoAppQueryTime;
    }

    /**
     * Sets the value of the pbocCoAppQueryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppQueryTime(BigDecimal value) {
        this.pbocCoAppQueryTime = value;
    }

    /**
     * Gets the value of the pbocCoAppLoanCLStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppLoanCLStatus() {
        return pbocCoAppLoanCLStatus;
    }

    /**
     * Sets the value of the pbocCoAppLoanCLStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppLoanCLStatus(BigDecimal value) {
        this.pbocCoAppLoanCLStatus = value;
    }

    /**
     * Gets the value of the pbocCoAppWorstFC property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppWorstFC() {
        return pbocCoAppWorstFC;
    }

    /**
     * Sets the value of the pbocCoAppWorstFC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppWorstFC(BigDecimal value) {
        this.pbocCoAppWorstFC = value;
    }

    /**
     * Gets the value of the pbocCoAppPhoneBillAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppPhoneBillAmount() {
        return pbocCoAppPhoneBillAmount;
    }

    /**
     * Sets the value of the pbocCoAppPhoneBillAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppPhoneBillAmount(BigDecimal value) {
        this.pbocCoAppPhoneBillAmount = value;
    }

    /**
     * Gets the value of the pbocCoAppPhonebillMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppPhonebillMonth() {
        return pbocCoAppPhonebillMonth;
    }

    /**
     * Sets the value of the pbocCoAppPhonebillMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppPhonebillMonth(BigDecimal value) {
        this.pbocCoAppPhonebillMonth = value;
    }

    /**
     * Gets the value of the pbocCoAppWorstFCForeign property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppWorstFCForeign() {
        return pbocCoAppWorstFCForeign;
    }

    /**
     * Sets the value of the pbocCoAppWorstFCForeign property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppWorstFCForeign(BigDecimal value) {
        this.pbocCoAppWorstFCForeign = value;
    }

    /**
     * Gets the value of the pbocCoAppQueryPQnum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppQueryPQnum() {
        return pbocCoAppQueryPQnum;
    }

    /**
     * Sets the value of the pbocCoAppQueryPQnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppQueryPQnum(BigDecimal value) {
        this.pbocCoAppQueryPQnum = value;
    }

    /**
     * Gets the value of the pbocCoAppQueryPYnum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppQueryPYnum() {
        return pbocCoAppQueryPYnum;
    }

    /**
     * Sets the value of the pbocCoAppQueryPYnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppQueryPYnum(BigDecimal value) {
        this.pbocCoAppQueryPYnum = value;
    }

    /**
     * Gets the value of the pbocCoAppTotalCL property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppTotalCL() {
        return pbocCoAppTotalCL;
    }

	/**
     * Sets the value of the pbocCoAppTotalCL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppTotalCL(BigDecimal value) {
        this.pbocCoAppTotalCL = value;
    }

    


    /**
     * Gets the value of the pbocCoAppUCloseAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppUCloseAmount() {
        return pbocCoAppUCloseAmount;
    }

    /**
     * Sets the value of the pbocCoAppUCloseAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppUCloseAmount(BigDecimal value) {
        this.pbocCoAppUCloseAmount = value;
    }

    /**
     * Gets the value of the pbocCoAppIsInvolved property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppIsInvolved() {
        return pbocCoAppIsInvolved;
    }

    /**
     * Sets the value of the pbocCoAppIsInvolved property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppIsInvolved(BigDecimal value) {
        this.pbocCoAppIsInvolved = value;
    }

    /**
     * Gets the value of the pbocCoAppMobilPhoone property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppMobilPhoone() {
        return pbocCoAppMobilPhoone;
    }

    /**
     * Sets the value of the pbocCoAppMobilPhoone property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppMobilPhoone(BigDecimal value) {
        this.pbocCoAppMobilPhoone = value;
    }

    /**
     * Gets the value of the pbocCoAppDCCLStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppDCCLStatus() {
        return pbocCoAppDCCLStatus;
    }

    /**
     * Sets the value of the pbocCoAppDCCLStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppDCCLStatus(BigDecimal value) {
        this.pbocCoAppDCCLStatus = value;
    }

    /**
     * Gets the value of the pbocCoAppDCWorstFC property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppDCWorstFC() {
        return pbocCoAppDCWorstFC;
    }

    /**
     * Sets the value of the pbocCoAppDCWorstFC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppDCWorstFC(BigDecimal value) {
        this.pbocCoAppDCWorstFC = value;
    }

    /**
     * Gets the value of the pbocCoAppDCAmountRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppDCAmountRate() {
        return pbocCoAppDCAmountRate;
    }

    /**
     * Sets the value of the pbocCoAppDCAmountRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppDCAmountRate(BigDecimal value) {
        this.pbocCoAppDCAmountRate = value;
    }

    /**
     * Gets the value of the pbocCoAppDCWorstState property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppDCWorstState() {
        return pbocCoAppDCWorstState;
    }

    /**
     * Sets the value of the pbocCoAppDCWorstState property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppDCWorstState(BigDecimal value) {
        this.pbocCoAppDCWorstState = value;
    }

    /**
     * Gets the value of the pbocCoAppCHMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppCHMonth() {
        return pbocCoAppCHMonth;
    }

    /**
     * Sets the value of the pbocCoAppCHMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppCHMonth(BigDecimal value) {
        this.pbocCoAppCHMonth = value;
    }

    /**
     * Gets the value of the pbocCoAppQueryMnum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppQueryMnum() {
        return pbocCoAppQueryMnum;
    }

    /**
     * Sets the value of the pbocCoAppQueryMnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppQueryMnum(BigDecimal value) {
        this.pbocCoAppQueryMnum = value;
    }

    /**
     * Gets the value of the pbocCoAppMaxCL property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppMaxCL() {
        return pbocCoAppMaxCL;
    }

    /**
     * Sets the value of the pbocCoAppMaxCL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppMaxCL(BigDecimal value) {
        this.pbocCoAppMaxCL = value;
    }

    /**
     * Gets the value of the pbocCoAppLateDueLAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public String getPBOCCoAppLateDueLAmount() {
        return pbocCoAppLateDueLAmount;
    }

    /**
     * Sets the value of the pbocCoAppLateDueLAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppLateDueLAmount(String value) {
        this.pbocCoAppLateDueLAmount = value;
    }

    

    /**
     * Gets the value of the pbocCoAppIsHistoryLoan property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCCoAppIsHistoryLoan() {
        return pbocCoAppIsHistoryLoan;
    }

    /**
     * Sets the value of the pbocCoAppIsHistoryLoan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCCoAppIsHistoryLoan(BigDecimal value) {
        this.pbocCoAppIsHistoryLoan = value;
    }

	

	public BigDecimal getPbocCoAppQueryTime() {
		return pbocCoAppQueryTime;
	}

	public void setPbocCoAppQueryTime(BigDecimal pbocCoAppQueryTime) {
		this.pbocCoAppQueryTime = pbocCoAppQueryTime;
	}

	public BigDecimal getPbocCoAppLoanCLStatus() {
		return pbocCoAppLoanCLStatus;
	}

	public void setPbocCoAppLoanCLStatus(BigDecimal pbocCoAppLoanCLStatus) {
		this.pbocCoAppLoanCLStatus = pbocCoAppLoanCLStatus;
	}

	public BigDecimal getPbocCoAppWorstFC() {
		return pbocCoAppWorstFC;
	}

	public void setPbocCoAppWorstFC(BigDecimal pbocCoAppWorstFC) {
		this.pbocCoAppWorstFC = pbocCoAppWorstFC;
	}

	public BigDecimal getPbocCoAppPhoneBillAmount() {
		return pbocCoAppPhoneBillAmount;
	}

	public void setPbocCoAppPhoneBillAmount(BigDecimal pbocCoAppPhoneBillAmount) {
		this.pbocCoAppPhoneBillAmount = pbocCoAppPhoneBillAmount;
	}

	public BigDecimal getPbocCoAppPhonebillMonth() {
		return pbocCoAppPhonebillMonth;
	}

	public void setPbocCoAppPhonebillMonth(BigDecimal pbocCoAppPhonebillMonth) {
		this.pbocCoAppPhonebillMonth = pbocCoAppPhonebillMonth;
	}

	public BigDecimal getPbocCoAppWorstFCForeign() {
		return pbocCoAppWorstFCForeign;
	}

	public void setPbocCoAppWorstFCForeign(BigDecimal pbocCoAppWorstFCForeign) {
		this.pbocCoAppWorstFCForeign = pbocCoAppWorstFCForeign;
	}

	public BigDecimal getPbocCoAppQueryPQnum() {
		return pbocCoAppQueryPQnum;
	}

	public void setPbocCoAppQueryPQnum(BigDecimal pbocCoAppQueryPQnum) {
		this.pbocCoAppQueryPQnum = pbocCoAppQueryPQnum;
	}

	public BigDecimal getPbocCoAppQueryPYnum() {
		return pbocCoAppQueryPYnum;
	}

	public void setPbocCoAppQueryPYnum(BigDecimal pbocCoAppQueryPYnum) {
		this.pbocCoAppQueryPYnum = pbocCoAppQueryPYnum;
	}

	public BigDecimal getPbocCoAppTotalCL() {
		return pbocCoAppTotalCL;
	}

	public void setPbocCoAppTotalCL(BigDecimal pbocCoAppTotalCL) {
		this.pbocCoAppTotalCL = pbocCoAppTotalCL;
	}


	public BigDecimal getPbocCoAppUCloseAmount() {
		return pbocCoAppUCloseAmount;
	}

	public void setPbocCoAppUCloseAmount(BigDecimal pbocCoAppUCloseAmount) {
		this.pbocCoAppUCloseAmount = pbocCoAppUCloseAmount;
	}

	public BigDecimal getPbocCoAppIsInvolved() {
		return pbocCoAppIsInvolved;
	}

	public void setPbocCoAppIsInvolved(BigDecimal pbocCoAppIsInvolved) {
		this.pbocCoAppIsInvolved = pbocCoAppIsInvolved;
	}

	public BigDecimal getPbocCoAppMobilPhoone() {
		return pbocCoAppMobilPhoone;
	}

	public void setPbocCoAppMobilPhoone(BigDecimal pbocCoAppMobilPhoone) {
		this.pbocCoAppMobilPhoone = pbocCoAppMobilPhoone;
	}

	public BigDecimal getPbocCoAppDCCLStatus() {
		return pbocCoAppDCCLStatus;
	}

	public void setPbocCoAppDCCLStatus(BigDecimal pbocCoAppDCCLStatus) {
		this.pbocCoAppDCCLStatus = pbocCoAppDCCLStatus;
	}

	public BigDecimal getPbocCoAppDCWorstFC() {
		return pbocCoAppDCWorstFC;
	}

	public void setPbocCoAppDCWorstFC(BigDecimal pbocCoAppDCWorstFC) {
		this.pbocCoAppDCWorstFC = pbocCoAppDCWorstFC;
	}

	public BigDecimal getPbocCoAppDCAmountRate() {
		return pbocCoAppDCAmountRate;
	}

	public void setPbocCoAppDCAmountRate(BigDecimal pbocCoAppDCAmountRate) {
		this.pbocCoAppDCAmountRate = pbocCoAppDCAmountRate;
	}

	public BigDecimal getPbocCoAppDCWorstState() {
		return pbocCoAppDCWorstState;
	}

	public void setPbocCoAppDCWorstState(BigDecimal pbocCoAppDCWorstState) {
		this.pbocCoAppDCWorstState = pbocCoAppDCWorstState;
	}

	public BigDecimal getPbocCoAppCHMonth() {
		return pbocCoAppCHMonth;
	}

	public void setPbocCoAppCHMonth(BigDecimal pbocCoAppCHMonth) {
		this.pbocCoAppCHMonth = pbocCoAppCHMonth;
	}

	public BigDecimal getPbocCoAppQueryMnum() {
		return pbocCoAppQueryMnum;
	}

	public void setPbocCoAppQueryMnum(BigDecimal pbocCoAppQueryMnum) {
		this.pbocCoAppQueryMnum = pbocCoAppQueryMnum;
	}

	public BigDecimal getPbocCoAppMaxCL() {
		return pbocCoAppMaxCL;
	}

	public void setPbocCoAppMaxCL(BigDecimal pbocCoAppMaxCL) {
		this.pbocCoAppMaxCL = pbocCoAppMaxCL;
	}

	public String getPbocCoAppLateDueLAmount() {
		return pbocCoAppLateDueLAmount;
	}

	public void setPbocCoAppLateDueLAmount(String pbocCoAppLateDueLAmount) {
		this.pbocCoAppLateDueLAmount = pbocCoAppLateDueLAmount;
	}



	public BigDecimal getPbocCoAppIsHistoryLoan() {
		return pbocCoAppIsHistoryLoan;
	}

	public void setPbocCoAppIsHistoryLoan(BigDecimal pbocCoAppIsHistoryLoan) {
		this.pbocCoAppIsHistoryLoan = pbocCoAppIsHistoryLoan;
	}

	public BigDecimal getPbocCoAppLoanNum() {
		return pbocCoAppLoanNum;
	}

	public void setPbocCoAppLoanNum(BigDecimal pbocCoAppLoanNum) {
		this.pbocCoAppLoanNum = pbocCoAppLoanNum;
	}

	public BigDecimal getPbocCoAppDCNum() {
		return pbocCoAppDCNum;
	}

	public void setPbocCoAppDCNum(BigDecimal pbocCoAppDCNum) {
		this.pbocCoAppDCNum = pbocCoAppDCNum;
	}

	public BigDecimal getPbocCoAppForeignNum() {
		return pbocCoAppForeignNum;
	}

	public void setPbocCoAppForeignNum(BigDecimal pbocCoAppForeignNum) {
		this.pbocCoAppForeignNum = pbocCoAppForeignNum;
	}

	public BigDecimal getPbocCoAppIsHavePL() {
		return pbocCoAppIsHavePL;
	}

	public void setPbocCoAppIsHavePL(BigDecimal pbocCoAppIsHavePL) {
		this.pbocCoAppIsHavePL = pbocCoAppIsHavePL;
	}

	public String getPbocCoAppRCTime() {
		return pbocCoAppRCTime;
	}

	public void setPbocCoAppRCTime(String pbocCoAppRCTime) {
		this.pbocCoAppRCTime = pbocCoAppRCTime;
	}

	public String getPbocCoAppLoanl50Due() {
		return pbocCoAppLoanl50Due;
	}

	public void setPbocCoAppLoanl50Due(String pbocCoAppLoanl50Due) {
		this.pbocCoAppLoanl50Due = pbocCoAppLoanl50Due;
	}

	public String getPbocCoAppLoanh50Due() {
		return pbocCoAppLoanh50Due;
	}

	public void setPbocCoAppLoanh50Due(String pbocCoAppLoanh50Due) {
		this.pbocCoAppLoanh50Due = pbocCoAppLoanh50Due;
	}

	public String getPbocCoAppLateDueLTime() {
		return pbocCoAppLateDueLTime;
	}

	public void setPbocCoAppLateDueLTime(String pbocCoAppLateDueLTime) {
		this.pbocCoAppLateDueLTime = pbocCoAppLateDueLTime;
	}
	
}
