//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 06:41:27 PM CST 
//


package com.resoft.outinterface.cn.com.experian.entry.request.body;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PBOC_FirmInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PBOC_FirmInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="PBOC_FIRM_RCTime" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PBOC_FIRM_QueryTime" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_FIRM_OfficePhone" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_FIRM_Worst_FC" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_FIRM_Worst_FC_Foreign" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_FIRM_CH_Month" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_FIRM_LateDueAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_FIRM_LateDueLTime" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PBOC_GuFirm_Worst_FC" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PBOC_FIRM_IsHistory_Loan" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PBOC_FirmInfo", propOrder = {
    "pbocfirmrcTime",
    "pbocfirmQueryTime",
    "pbocfirmOfficePhone",
    "pbocfirmWorstFC",
    "pbocfirmWorstFCForeign",
    "pbocfirmchMonth",
    "pbocfirmLateDueAmount",
    "pbocfirmLateDueLTime",
    "pbocGuFirmWorstFC",
    "pbocfirmIsHistoryLoan",
    "pbocfirmLoanNum",
    "pbocfirmDCNum",
    "pbocfirmForeignNum",
    "pbocfirmIsHavePL"
})
public class PBOCFirmInfo {

    @XmlElement(name = "PBOC_FIRM_RCTime")
    @XmlSchemaType(name = "date")
    protected String pbocfirmrcTime;
    @XmlElement(name = "PBOC_FIRM_QueryTime")
    protected BigDecimal pbocfirmQueryTime;
    @XmlElement(name = "PBOC_FIRM_OfficePhone")
    protected BigDecimal pbocfirmOfficePhone;
    @XmlElement(name = "PBOC_FIRM_Worst_FC")
    protected BigDecimal pbocfirmWorstFC;
    @XmlElement(name = "PBOC_FIRM_Worst_FC_Foreign")
    protected BigDecimal pbocfirmWorstFCForeign;
    @XmlElement(name = "PBOC_FIRM_CH_Month")
    protected BigDecimal pbocfirmchMonth;
    @XmlElement(name = "PBOC_FIRM_LateDueAmount")
    protected BigDecimal pbocfirmLateDueAmount;
    @XmlElement(name = "PBOC_FIRM_LateDueLTime")
    @XmlSchemaType(name = "date")
    protected String pbocfirmLateDueLTime;
    @XmlElement(name = "PBOC_GuFirm_Worst_FC")
    protected BigDecimal pbocGuFirmWorstFC;
    @XmlElement(name = "PBOC_FIRM_IsHistory_Loan")
    protected BigDecimal pbocfirmIsHistoryLoan;
    @XmlElement(name = "PBOC_FIRM_loan_num")
    protected BigDecimal pbocfirmLoanNum;
    @XmlElement(name = "PBOC_FIRM_DC_num")
    protected BigDecimal pbocfirmDCNum;
    @XmlElement(name = "PBOC_FIRM_Foreign_num")
    protected BigDecimal pbocfirmForeignNum;
    @XmlElement(name = "PBOC_FIRM_IsHavePL")
    protected BigDecimal pbocfirmIsHavePL;
    
    

    /**
     * Gets the value of the pbocfirmQueryTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCFIRMQueryTime() {
        return pbocfirmQueryTime;
    }

    /**
     * Sets the value of the pbocfirmQueryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCFIRMQueryTime(BigDecimal value) {
        this.pbocfirmQueryTime = value;
    }

    /**
     * Gets the value of the pbocfirmOfficePhone property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCFIRMOfficePhone() {
        return pbocfirmOfficePhone;
    }

    /**
     * Sets the value of the pbocfirmOfficePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCFIRMOfficePhone(BigDecimal value) {
        this.pbocfirmOfficePhone = value;
    }

    /**
     * Gets the value of the pbocfirmWorstFC property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    
    public BigDecimal getPBOCFIRMWorstFC() {
        return pbocfirmWorstFC;
    }

    

	public BigDecimal getPbocfirmQueryTime() {
		return pbocfirmQueryTime;
	}

	public void setPbocfirmQueryTime(BigDecimal pbocfirmQueryTime) {
		this.pbocfirmQueryTime = pbocfirmQueryTime;
	}

	public BigDecimal getPbocfirmOfficePhone() {
		return pbocfirmOfficePhone;
	}

	public void setPbocfirmOfficePhone(BigDecimal pbocfirmOfficePhone) {
		this.pbocfirmOfficePhone = pbocfirmOfficePhone;
	}

	public BigDecimal getPbocfirmWorstFC() {
		return pbocfirmWorstFC;
	}

	public void setPbocfirmWorstFC(BigDecimal pbocfirmWorstFC) {
		this.pbocfirmWorstFC = pbocfirmWorstFC;
	}

	public BigDecimal getPbocfirmWorstFCForeign() {
		return pbocfirmWorstFCForeign;
	}

	public void setPbocfirmWorstFCForeign(BigDecimal pbocfirmWorstFCForeign) {
		this.pbocfirmWorstFCForeign = pbocfirmWorstFCForeign;
	}

	public BigDecimal getPbocfirmchMonth() {
		return pbocfirmchMonth;
	}

	public void setPbocfirmchMonth(BigDecimal pbocfirmchMonth) {
		this.pbocfirmchMonth = pbocfirmchMonth;
	}

	public BigDecimal getPbocfirmLateDueAmount() {
		return pbocfirmLateDueAmount;
	}

	public void setPbocfirmLateDueAmount(BigDecimal pbocfirmLateDueAmount) {
		this.pbocfirmLateDueAmount = pbocfirmLateDueAmount;
	}

	

	public BigDecimal getPbocGuFirmWorstFC() {
		return pbocGuFirmWorstFC;
	}

	public void setPbocGuFirmWorstFC(BigDecimal pbocGuFirmWorstFC) {
		this.pbocGuFirmWorstFC = pbocGuFirmWorstFC;
	}

	public BigDecimal getPbocfirmIsHistoryLoan() {
		return pbocfirmIsHistoryLoan;
	}

	public void setPbocfirmIsHistoryLoan(BigDecimal pbocfirmIsHistoryLoan) {
		this.pbocfirmIsHistoryLoan = pbocfirmIsHistoryLoan;
	}

	/**
     * Sets the value of the pbocfirmWorstFC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCFIRMWorstFC(BigDecimal value) {
        this.pbocfirmWorstFC = value;
    }

    /**
     * Gets the value of the pbocfirmWorstFCForeign property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCFIRMWorstFCForeign() {
        return pbocfirmWorstFCForeign;
    }

    /**
     * Sets the value of the pbocfirmWorstFCForeign property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCFIRMWorstFCForeign(BigDecimal value) {
        this.pbocfirmWorstFCForeign = value;
    }

    /**
     * Gets the value of the pbocfirmchMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCFIRMCHMonth() {
        return pbocfirmchMonth;
    }

	/**
     * Sets the value of the pbocfirmchMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCFIRMCHMonth(BigDecimal value) {
        this.pbocfirmchMonth = value;
    }

    /**
     * Gets the value of the pbocfirmLateDueAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCFIRMLateDueAmount() {
        return pbocfirmLateDueAmount;
    }

    /**
     * Sets the value of the pbocfirmLateDueAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCFIRMLateDueAmount(BigDecimal value) {
        this.pbocfirmLateDueAmount = value;
    }

    

    /**
     * Gets the value of the pbocGuFirmWorstFC property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCGuFirmWorstFC() {
        return pbocGuFirmWorstFC;
    }

    /**
     * Sets the value of the pbocGuFirmWorstFC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCGuFirmWorstFC(BigDecimal value) {
        this.pbocGuFirmWorstFC = value;
    }

    /**
     * Gets the value of the pbocfirmIsHistoryLoan property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPBOCFIRMIsHistoryLoan() {
        return pbocfirmIsHistoryLoan;
    }

    /**
     * Sets the value of the pbocfirmIsHistoryLoan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPBOCFIRMIsHistoryLoan(BigDecimal value) {
        this.pbocfirmIsHistoryLoan = value;
    }

	public BigDecimal getPbocfirmLoanNum() {
		return pbocfirmLoanNum;
	}

	public void setPbocfirmLoanNum(BigDecimal pbocfirmLoanNum) {
		this.pbocfirmLoanNum = pbocfirmLoanNum;
	}

	public BigDecimal getPbocfirmDCNum() {
		return pbocfirmDCNum;
	}

	public void setPbocfirmDCNum(BigDecimal pbocfirmDCNum) {
		this.pbocfirmDCNum = pbocfirmDCNum;
	}

	public BigDecimal getPbocfirmForeignNum() {
		return pbocfirmForeignNum;
	}

	public void setPbocfirmForeignNum(BigDecimal pbocfirmForeignNum) {
		this.pbocfirmForeignNum = pbocfirmForeignNum;
	}

	public BigDecimal getPbocfirmIsHavePL() {
		return pbocfirmIsHavePL;
	}

	public void setPbocfirmIsHavePL(BigDecimal pbocfirmIsHavePL) {
		this.pbocfirmIsHavePL = pbocfirmIsHavePL;
	}

	public String getPbocfirmrcTime() {
		return pbocfirmrcTime;
	}

	public void setPbocfirmrcTime(String pbocfirmrcTime) {
		this.pbocfirmrcTime = pbocfirmrcTime;
	}

	public String getPbocfirmLateDueLTime() {
		return pbocfirmLateDueLTime;
	}

	public void setPbocfirmLateDueLTime(String pbocfirmLateDueLTime) {
		this.pbocfirmLateDueLTime = pbocfirmLateDueLTime;
	}

}
